// Code generated by proto-gen. DO NOT EDIT.
// Source: SRPC method definitions in rpcd/
//
// To regenerate this file, run:
//   make proto-gen
// or:
//   proto-gen --rpcd <rpcd-dir> --proto <proto-dir> --output <output-file>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: hypervisor.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AcknowledgeVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeVmResponse) Reset() {
	*x = AcknowledgeVmResponse{}
	mi := &file_hypervisor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeVmResponse) ProtoMessage() {}

func (x *AcknowledgeVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hypervisor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeVmResponse.ProtoReflect.Descriptor instead.
func (*AcknowledgeVmResponse) Descriptor() ([]byte, []int) {
	return file_hypervisor_proto_rawDescGZIP(), []int{0}
}

type GetVmInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpAddress     []byte                 `protobuf:"bytes,1,opt,name=IpAddress,proto3" json:"IpAddress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVmInfoRequest) Reset() {
	*x = GetVmInfoRequest{}
	mi := &file_hypervisor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVmInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVmInfoRequest) ProtoMessage() {}

func (x *GetVmInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hypervisor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVmInfoRequest.ProtoReflect.Descriptor instead.
func (*GetVmInfoRequest) Descriptor() ([]byte, []int) {
	return file_hypervisor_proto_rawDescGZIP(), []int{1}
}

func (x *GetVmInfoRequest) GetIpAddress() []byte {
	if x != nil {
		return x.IpAddress
	}
	return nil
}

type GetVmInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmInfo        *VmInfo                `protobuf:"bytes,1,opt,name=VmInfo,proto3" json:"VmInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVmInfoResponse) Reset() {
	*x = GetVmInfoResponse{}
	mi := &file_hypervisor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVmInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVmInfoResponse) ProtoMessage() {}

func (x *GetVmInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hypervisor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVmInfoResponse.ProtoReflect.Descriptor instead.
func (*GetVmInfoResponse) Descriptor() ([]byte, []int) {
	return file_hypervisor_proto_rawDescGZIP(), []int{2}
}

func (x *GetVmInfoResponse) GetVmInfo() *VmInfo {
	if x != nil {
		return x.VmInfo
	}
	return nil
}

type AcknowledgeVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpAddress     []byte                 `protobuf:"bytes,1,opt,name=IpAddress,proto3" json:"IpAddress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeVmRequest) Reset() {
	*x = AcknowledgeVmRequest{}
	mi := &file_hypervisor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeVmRequest) ProtoMessage() {}

func (x *AcknowledgeVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hypervisor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeVmRequest.ProtoReflect.Descriptor instead.
func (*AcknowledgeVmRequest) Descriptor() ([]byte, []int) {
	return file_hypervisor_proto_rawDescGZIP(), []int{3}
}

func (x *AcknowledgeVmRequest) GetIpAddress() []byte {
	if x != nil {
		return x.IpAddress
	}
	return nil
}

type VmInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Address             *Address               `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	ChangedStateOn      int64                  `protobuf:"varint,2,opt,name=ChangedStateOn,proto3" json:"ChangedStateOn,omitempty"`
	ConsoleType         uint32                 `protobuf:"varint,3,opt,name=ConsoleType,proto3" json:"ConsoleType,omitempty"`
	CreatedOn           int64                  `protobuf:"varint,4,opt,name=CreatedOn,proto3" json:"CreatedOn,omitempty"`
	CpuPriority         int32                  `protobuf:"varint,5,opt,name=CpuPriority,proto3" json:"CpuPriority,omitempty"`
	DestroyOnPowerdown  bool                   `protobuf:"varint,6,opt,name=DestroyOnPowerdown,proto3" json:"DestroyOnPowerdown,omitempty"`
	DestroyProtection   bool                   `protobuf:"varint,7,opt,name=DestroyProtection,proto3" json:"DestroyProtection,omitempty"`
	DisableVirtIO       bool                   `protobuf:"varint,8,opt,name=DisableVirtIO,proto3" json:"DisableVirtIO,omitempty"`
	ExtraKernelOptions  string                 `protobuf:"bytes,9,opt,name=ExtraKernelOptions,proto3" json:"ExtraKernelOptions,omitempty"`
	FirmwareType        uint32                 `protobuf:"varint,10,opt,name=FirmwareType,proto3" json:"FirmwareType,omitempty"`
	Hostname            string                 `protobuf:"bytes,11,opt,name=Hostname,proto3" json:"Hostname,omitempty"`
	IdentityExpires     int64                  `protobuf:"varint,12,opt,name=IdentityExpires,proto3" json:"IdentityExpires,omitempty"`
	IdentityName        string                 `protobuf:"bytes,13,opt,name=IdentityName,proto3" json:"IdentityName,omitempty"`
	ImageName           string                 `protobuf:"bytes,14,opt,name=ImageName,proto3" json:"ImageName,omitempty"`
	ImageURL            string                 `protobuf:"bytes,15,opt,name=ImageURL,proto3" json:"ImageURL,omitempty"`
	MachineType         uint32                 `protobuf:"varint,16,opt,name=MachineType,proto3" json:"MachineType,omitempty"`
	MemoryInMiB         uint64                 `protobuf:"varint,17,opt,name=MemoryInMiB,proto3" json:"MemoryInMiB,omitempty"`
	MilliCPUs           uint32                 `protobuf:"varint,18,opt,name=MilliCPUs,proto3" json:"MilliCPUs,omitempty"`
	NetworkEntries      []*NetworkEntry        `protobuf:"bytes,19,rep,name=NetworkEntries,proto3" json:"NetworkEntries,omitempty"`
	OwnerGroups         []string               `protobuf:"bytes,20,rep,name=OwnerGroups,proto3" json:"OwnerGroups,omitempty"`
	OwnerUsers          []string               `protobuf:"bytes,21,rep,name=OwnerUsers,proto3" json:"OwnerUsers,omitempty"`
	RootFileSystemLabel string                 `protobuf:"bytes,22,opt,name=RootFileSystemLabel,proto3" json:"RootFileSystemLabel,omitempty"`
	SpreadVolumes       bool                   `protobuf:"varint,23,opt,name=SpreadVolumes,proto3" json:"SpreadVolumes,omitempty"`
	State               uint32                 `protobuf:"varint,24,opt,name=State,proto3" json:"State,omitempty"`
	SecondaryAddresses  []*Address             `protobuf:"bytes,25,rep,name=SecondaryAddresses,proto3" json:"SecondaryAddresses,omitempty"`
	SecondarySubnetIDs  []string               `protobuf:"bytes,26,rep,name=SecondarySubnetIDs,proto3" json:"SecondarySubnetIDs,omitempty"`
	SubnetId            string                 `protobuf:"bytes,27,opt,name=SubnetId,proto3" json:"SubnetId,omitempty"`
	Tags                map[string]string      `protobuf:"bytes,28,rep,name=Tags,proto3" json:"Tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Uncommitted         bool                   `protobuf:"varint,29,opt,name=Uncommitted,proto3" json:"Uncommitted,omitempty"`
	VirtualCPUs         uint32                 `protobuf:"varint,30,opt,name=VirtualCPUs,proto3" json:"VirtualCPUs,omitempty"`
	Volumes             []*Volume              `protobuf:"bytes,31,rep,name=Volumes,proto3" json:"Volumes,omitempty"`
	WatchdogAction      uint32                 `protobuf:"varint,32,opt,name=WatchdogAction,proto3" json:"WatchdogAction,omitempty"`
	WatchdogModel       uint32                 `protobuf:"varint,33,opt,name=WatchdogModel,proto3" json:"WatchdogModel,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *VmInfo) Reset() {
	*x = VmInfo{}
	mi := &file_hypervisor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmInfo) ProtoMessage() {}

func (x *VmInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hypervisor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmInfo.ProtoReflect.Descriptor instead.
func (*VmInfo) Descriptor() ([]byte, []int) {
	return file_hypervisor_proto_rawDescGZIP(), []int{4}
}

func (x *VmInfo) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *VmInfo) GetChangedStateOn() int64 {
	if x != nil {
		return x.ChangedStateOn
	}
	return 0
}

func (x *VmInfo) GetConsoleType() uint32 {
	if x != nil {
		return x.ConsoleType
	}
	return 0
}

func (x *VmInfo) GetCreatedOn() int64 {
	if x != nil {
		return x.CreatedOn
	}
	return 0
}

func (x *VmInfo) GetCpuPriority() int32 {
	if x != nil {
		return x.CpuPriority
	}
	return 0
}

func (x *VmInfo) GetDestroyOnPowerdown() bool {
	if x != nil {
		return x.DestroyOnPowerdown
	}
	return false
}

func (x *VmInfo) GetDestroyProtection() bool {
	if x != nil {
		return x.DestroyProtection
	}
	return false
}

func (x *VmInfo) GetDisableVirtIO() bool {
	if x != nil {
		return x.DisableVirtIO
	}
	return false
}

func (x *VmInfo) GetExtraKernelOptions() string {
	if x != nil {
		return x.ExtraKernelOptions
	}
	return ""
}

func (x *VmInfo) GetFirmwareType() uint32 {
	if x != nil {
		return x.FirmwareType
	}
	return 0
}

func (x *VmInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *VmInfo) GetIdentityExpires() int64 {
	if x != nil {
		return x.IdentityExpires
	}
	return 0
}

func (x *VmInfo) GetIdentityName() string {
	if x != nil {
		return x.IdentityName
	}
	return ""
}

func (x *VmInfo) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *VmInfo) GetImageURL() string {
	if x != nil {
		return x.ImageURL
	}
	return ""
}

func (x *VmInfo) GetMachineType() uint32 {
	if x != nil {
		return x.MachineType
	}
	return 0
}

func (x *VmInfo) GetMemoryInMiB() uint64 {
	if x != nil {
		return x.MemoryInMiB
	}
	return 0
}

func (x *VmInfo) GetMilliCPUs() uint32 {
	if x != nil {
		return x.MilliCPUs
	}
	return 0
}

func (x *VmInfo) GetNetworkEntries() []*NetworkEntry {
	if x != nil {
		return x.NetworkEntries
	}
	return nil
}

func (x *VmInfo) GetOwnerGroups() []string {
	if x != nil {
		return x.OwnerGroups
	}
	return nil
}

func (x *VmInfo) GetOwnerUsers() []string {
	if x != nil {
		return x.OwnerUsers
	}
	return nil
}

func (x *VmInfo) GetRootFileSystemLabel() string {
	if x != nil {
		return x.RootFileSystemLabel
	}
	return ""
}

func (x *VmInfo) GetSpreadVolumes() bool {
	if x != nil {
		return x.SpreadVolumes
	}
	return false
}

func (x *VmInfo) GetState() uint32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *VmInfo) GetSecondaryAddresses() []*Address {
	if x != nil {
		return x.SecondaryAddresses
	}
	return nil
}

func (x *VmInfo) GetSecondarySubnetIDs() []string {
	if x != nil {
		return x.SecondarySubnetIDs
	}
	return nil
}

func (x *VmInfo) GetSubnetId() string {
	if x != nil {
		return x.SubnetId
	}
	return ""
}

func (x *VmInfo) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *VmInfo) GetUncommitted() bool {
	if x != nil {
		return x.Uncommitted
	}
	return false
}

func (x *VmInfo) GetVirtualCPUs() uint32 {
	if x != nil {
		return x.VirtualCPUs
	}
	return 0
}

func (x *VmInfo) GetVolumes() []*Volume {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *VmInfo) GetWatchdogAction() uint32 {
	if x != nil {
		return x.WatchdogAction
	}
	return 0
}

func (x *VmInfo) GetWatchdogModel() uint32 {
	if x != nil {
		return x.WatchdogModel
	}
	return 0
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpAddress     []byte                 `protobuf:"bytes,1,opt,name=IpAddress,proto3" json:"IpAddress,omitempty"`
	MacAddress    string                 `protobuf:"bytes,2,opt,name=MacAddress,proto3" json:"MacAddress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_hypervisor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_hypervisor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_hypervisor_proto_rawDescGZIP(), []int{5}
}

func (x *Address) GetIpAddress() []byte {
	if x != nil {
		return x.IpAddress
	}
	return nil
}

func (x *Address) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

type NetworkEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumQueues     uint32                 `protobuf:"varint,1,opt,name=NumQueues,proto3" json:"NumQueues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkEntry) Reset() {
	*x = NetworkEntry{}
	mi := &file_hypervisor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkEntry) ProtoMessage() {}

func (x *NetworkEntry) ProtoReflect() protoreflect.Message {
	mi := &file_hypervisor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkEntry.ProtoReflect.Descriptor instead.
func (*NetworkEntry) Descriptor() ([]byte, []int) {
	return file_hypervisor_proto_rawDescGZIP(), []int{6}
}

func (x *NetworkEntry) GetNumQueues() uint32 {
	if x != nil {
		return x.NumQueues
	}
	return 0
}

type Volume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        uint32                 `protobuf:"varint,1,opt,name=Format,proto3" json:"Format,omitempty"`
	Interface     uint32                 `protobuf:"varint,2,opt,name=Interface,proto3" json:"Interface,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=Size,proto3" json:"Size,omitempty"`
	Snapshots     map[string]uint64      `protobuf:"bytes,4,rep,name=Snapshots,proto3" json:"Snapshots,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Type          uint32                 `protobuf:"varint,5,opt,name=Type,proto3" json:"Type,omitempty"`
	VirtualSize   uint64                 `protobuf:"varint,6,opt,name=VirtualSize,proto3" json:"VirtualSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Volume) Reset() {
	*x = Volume{}
	mi := &file_hypervisor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Volume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Volume) ProtoMessage() {}

func (x *Volume) ProtoReflect() protoreflect.Message {
	mi := &file_hypervisor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Volume.ProtoReflect.Descriptor instead.
func (*Volume) Descriptor() ([]byte, []int) {
	return file_hypervisor_proto_rawDescGZIP(), []int{7}
}

func (x *Volume) GetFormat() uint32 {
	if x != nil {
		return x.Format
	}
	return 0
}

func (x *Volume) GetInterface() uint32 {
	if x != nil {
		return x.Interface
	}
	return 0
}

func (x *Volume) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Volume) GetSnapshots() map[string]uint64 {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

func (x *Volume) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Volume) GetVirtualSize() uint64 {
	if x != nil {
		return x.VirtualSize
	}
	return 0
}

var File_hypervisor_proto protoreflect.FileDescriptor

const file_hypervisor_proto_rawDesc = "" +
	"\n" +
	"\x10hypervisor.proto\x12\n" +
	"hypervisor\"\x17\n" +
	"\x15AcknowledgeVmResponse\"0\n" +
	"\x10GetVmInfoRequest\x12\x1c\n" +
	"\tIpAddress\x18\x01 \x01(\fR\tIpAddress\"?\n" +
	"\x11GetVmInfoResponse\x12*\n" +
	"\x06VmInfo\x18\x01 \x01(\v2\x12.hypervisor.VmInfoR\x06VmInfo\"4\n" +
	"\x14AcknowledgeVmRequest\x12\x1c\n" +
	"\tIpAddress\x18\x01 \x01(\fR\tIpAddress\"\xcd\n" +
	"\n" +
	"\x06VmInfo\x12-\n" +
	"\aAddress\x18\x01 \x01(\v2\x13.hypervisor.AddressR\aAddress\x12&\n" +
	"\x0eChangedStateOn\x18\x02 \x01(\x03R\x0eChangedStateOn\x12 \n" +
	"\vConsoleType\x18\x03 \x01(\rR\vConsoleType\x12\x1c\n" +
	"\tCreatedOn\x18\x04 \x01(\x03R\tCreatedOn\x12 \n" +
	"\vCpuPriority\x18\x05 \x01(\x05R\vCpuPriority\x12.\n" +
	"\x12DestroyOnPowerdown\x18\x06 \x01(\bR\x12DestroyOnPowerdown\x12,\n" +
	"\x11DestroyProtection\x18\a \x01(\bR\x11DestroyProtection\x12$\n" +
	"\rDisableVirtIO\x18\b \x01(\bR\rDisableVirtIO\x12.\n" +
	"\x12ExtraKernelOptions\x18\t \x01(\tR\x12ExtraKernelOptions\x12\"\n" +
	"\fFirmwareType\x18\n" +
	" \x01(\rR\fFirmwareType\x12\x1a\n" +
	"\bHostname\x18\v \x01(\tR\bHostname\x12(\n" +
	"\x0fIdentityExpires\x18\f \x01(\x03R\x0fIdentityExpires\x12\"\n" +
	"\fIdentityName\x18\r \x01(\tR\fIdentityName\x12\x1c\n" +
	"\tImageName\x18\x0e \x01(\tR\tImageName\x12\x1a\n" +
	"\bImageURL\x18\x0f \x01(\tR\bImageURL\x12 \n" +
	"\vMachineType\x18\x10 \x01(\rR\vMachineType\x12 \n" +
	"\vMemoryInMiB\x18\x11 \x01(\x04R\vMemoryInMiB\x12\x1c\n" +
	"\tMilliCPUs\x18\x12 \x01(\rR\tMilliCPUs\x12@\n" +
	"\x0eNetworkEntries\x18\x13 \x03(\v2\x18.hypervisor.NetworkEntryR\x0eNetworkEntries\x12 \n" +
	"\vOwnerGroups\x18\x14 \x03(\tR\vOwnerGroups\x12\x1e\n" +
	"\n" +
	"OwnerUsers\x18\x15 \x03(\tR\n" +
	"OwnerUsers\x120\n" +
	"\x13RootFileSystemLabel\x18\x16 \x01(\tR\x13RootFileSystemLabel\x12$\n" +
	"\rSpreadVolumes\x18\x17 \x01(\bR\rSpreadVolumes\x12\x14\n" +
	"\x05State\x18\x18 \x01(\rR\x05State\x12C\n" +
	"\x12SecondaryAddresses\x18\x19 \x03(\v2\x13.hypervisor.AddressR\x12SecondaryAddresses\x12.\n" +
	"\x12SecondarySubnetIDs\x18\x1a \x03(\tR\x12SecondarySubnetIDs\x12\x1a\n" +
	"\bSubnetId\x18\x1b \x01(\tR\bSubnetId\x120\n" +
	"\x04Tags\x18\x1c \x03(\v2\x1c.hypervisor.VmInfo.TagsEntryR\x04Tags\x12 \n" +
	"\vUncommitted\x18\x1d \x01(\bR\vUncommitted\x12 \n" +
	"\vVirtualCPUs\x18\x1e \x01(\rR\vVirtualCPUs\x12,\n" +
	"\aVolumes\x18\x1f \x03(\v2\x12.hypervisor.VolumeR\aVolumes\x12&\n" +
	"\x0eWatchdogAction\x18  \x01(\rR\x0eWatchdogAction\x12$\n" +
	"\rWatchdogModel\x18! \x01(\rR\rWatchdogModel\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\aAddress\x12\x1c\n" +
	"\tIpAddress\x18\x01 \x01(\fR\tIpAddress\x12\x1e\n" +
	"\n" +
	"MacAddress\x18\x02 \x01(\tR\n" +
	"MacAddress\",\n" +
	"\fNetworkEntry\x12\x1c\n" +
	"\tNumQueues\x18\x01 \x01(\rR\tNumQueues\"\x87\x02\n" +
	"\x06Volume\x12\x16\n" +
	"\x06Format\x18\x01 \x01(\rR\x06Format\x12\x1c\n" +
	"\tInterface\x18\x02 \x01(\rR\tInterface\x12\x12\n" +
	"\x04Size\x18\x03 \x01(\x04R\x04Size\x12?\n" +
	"\tSnapshots\x18\x04 \x03(\v2!.hypervisor.Volume.SnapshotsEntryR\tSnapshots\x12\x12\n" +
	"\x04Type\x18\x05 \x01(\rR\x04Type\x12 \n" +
	"\vVirtualSize\x18\x06 \x01(\x04R\vVirtualSize\x1a<\n" +
	"\x0eSnapshotsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x012\xac\x01\n" +
	"\n" +
	"Hypervisor\x12T\n" +
	"\rAcknowledgeVm\x12 .hypervisor.AcknowledgeVmRequest\x1a!.hypervisor.AcknowledgeVmResponse\x12H\n" +
	"\tGetVmInfo\x12\x1c.hypervisor.GetVmInfoRequest\x1a\x1d.hypervisor.GetVmInfoResponseB\x06Z\x04.;pbb\x06proto3"

var (
	file_hypervisor_proto_rawDescOnce sync.Once
	file_hypervisor_proto_rawDescData []byte
)

func file_hypervisor_proto_rawDescGZIP() []byte {
	file_hypervisor_proto_rawDescOnce.Do(func() {
		file_hypervisor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hypervisor_proto_rawDesc), len(file_hypervisor_proto_rawDesc)))
	})
	return file_hypervisor_proto_rawDescData
}

var file_hypervisor_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_hypervisor_proto_goTypes = []any{
	(*AcknowledgeVmResponse)(nil), // 0: hypervisor.AcknowledgeVmResponse
	(*GetVmInfoRequest)(nil),      // 1: hypervisor.GetVmInfoRequest
	(*GetVmInfoResponse)(nil),     // 2: hypervisor.GetVmInfoResponse
	(*AcknowledgeVmRequest)(nil),  // 3: hypervisor.AcknowledgeVmRequest
	(*VmInfo)(nil),                // 4: hypervisor.VmInfo
	(*Address)(nil),               // 5: hypervisor.Address
	(*NetworkEntry)(nil),          // 6: hypervisor.NetworkEntry
	(*Volume)(nil),                // 7: hypervisor.Volume
	nil,                           // 8: hypervisor.VmInfo.TagsEntry
	nil,                           // 9: hypervisor.Volume.SnapshotsEntry
}
var file_hypervisor_proto_depIdxs = []int32{
	4, // 0: hypervisor.GetVmInfoResponse.VmInfo:type_name -> hypervisor.VmInfo
	5, // 1: hypervisor.VmInfo.Address:type_name -> hypervisor.Address
	6, // 2: hypervisor.VmInfo.NetworkEntries:type_name -> hypervisor.NetworkEntry
	5, // 3: hypervisor.VmInfo.SecondaryAddresses:type_name -> hypervisor.Address
	8, // 4: hypervisor.VmInfo.Tags:type_name -> hypervisor.VmInfo.TagsEntry
	7, // 5: hypervisor.VmInfo.Volumes:type_name -> hypervisor.Volume
	9, // 6: hypervisor.Volume.Snapshots:type_name -> hypervisor.Volume.SnapshotsEntry
	3, // 7: hypervisor.Hypervisor.AcknowledgeVm:input_type -> hypervisor.AcknowledgeVmRequest
	1, // 8: hypervisor.Hypervisor.GetVmInfo:input_type -> hypervisor.GetVmInfoRequest
	0, // 9: hypervisor.Hypervisor.AcknowledgeVm:output_type -> hypervisor.AcknowledgeVmResponse
	2, // 10: hypervisor.Hypervisor.GetVmInfo:output_type -> hypervisor.GetVmInfoResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_hypervisor_proto_init() }
func file_hypervisor_proto_init() {
	if File_hypervisor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hypervisor_proto_rawDesc), len(file_hypervisor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hypervisor_proto_goTypes,
		DependencyIndexes: file_hypervisor_proto_depIdxs,
		MessageInfos:      file_hypervisor_proto_msgTypes,
	}.Build()
	File_hypervisor_proto = out.File
	file_hypervisor_proto_goTypes = nil
	file_hypervisor_proto_depIdxs = nil
}
