// Code generated by proto-gen. DO NOT EDIT.
// Source: SRPC method definitions in rpcd/
//
// To regenerate this file, run:
//   make proto-gen
// or:
//   proto-gen --rpcd <rpcd-dir> --proto <proto-dir> --output <output-file>

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: hypervisor.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Hypervisor_AcknowledgeVm_FullMethodName = "/hypervisor.Hypervisor/AcknowledgeVm"
	Hypervisor_GetVmInfo_FullMethodName     = "/hypervisor.Hypervisor/GetVmInfo"
)

// HypervisorClient is the client API for Hypervisor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HypervisorClient interface {
	AcknowledgeVm(ctx context.Context, in *AcknowledgeVmRequest, opts ...grpc.CallOption) (*AcknowledgeVmResponse, error)
	GetVmInfo(ctx context.Context, in *GetVmInfoRequest, opts ...grpc.CallOption) (*GetVmInfoResponse, error)
}

type hypervisorClient struct {
	cc grpc.ClientConnInterface
}

func NewHypervisorClient(cc grpc.ClientConnInterface) HypervisorClient {
	return &hypervisorClient{cc}
}

func (c *hypervisorClient) AcknowledgeVm(ctx context.Context, in *AcknowledgeVmRequest, opts ...grpc.CallOption) (*AcknowledgeVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcknowledgeVmResponse)
	err := c.cc.Invoke(ctx, Hypervisor_AcknowledgeVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hypervisorClient) GetVmInfo(ctx context.Context, in *GetVmInfoRequest, opts ...grpc.CallOption) (*GetVmInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVmInfoResponse)
	err := c.cc.Invoke(ctx, Hypervisor_GetVmInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HypervisorServer is the server API for Hypervisor service.
// All implementations must embed UnimplementedHypervisorServer
// for forward compatibility.
type HypervisorServer interface {
	AcknowledgeVm(context.Context, *AcknowledgeVmRequest) (*AcknowledgeVmResponse, error)
	GetVmInfo(context.Context, *GetVmInfoRequest) (*GetVmInfoResponse, error)
	mustEmbedUnimplementedHypervisorServer()
}

// UnimplementedHypervisorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHypervisorServer struct{}

func (UnimplementedHypervisorServer) AcknowledgeVm(context.Context, *AcknowledgeVmRequest) (*AcknowledgeVmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcknowledgeVm not implemented")
}
func (UnimplementedHypervisorServer) GetVmInfo(context.Context, *GetVmInfoRequest) (*GetVmInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVmInfo not implemented")
}
func (UnimplementedHypervisorServer) mustEmbedUnimplementedHypervisorServer() {}
func (UnimplementedHypervisorServer) testEmbeddedByValue()                    {}

// UnsafeHypervisorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HypervisorServer will
// result in compilation errors.
type UnsafeHypervisorServer interface {
	mustEmbedUnimplementedHypervisorServer()
}

func RegisterHypervisorServer(s grpc.ServiceRegistrar, srv HypervisorServer) {
	// If the following call panics, it indicates UnimplementedHypervisorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Hypervisor_ServiceDesc, srv)
}

func _Hypervisor_AcknowledgeVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HypervisorServer).AcknowledgeVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hypervisor_AcknowledgeVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HypervisorServer).AcknowledgeVm(ctx, req.(*AcknowledgeVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hypervisor_GetVmInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVmInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HypervisorServer).GetVmInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hypervisor_GetVmInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HypervisorServer).GetVmInfo(ctx, req.(*GetVmInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Hypervisor_ServiceDesc is the grpc.ServiceDesc for Hypervisor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hypervisor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hypervisor.Hypervisor",
	HandlerType: (*HypervisorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AcknowledgeVm",
			Handler:    _Hypervisor_AcknowledgeVm_Handler,
		},
		{
			MethodName: "GetVmInfo",
			Handler:    _Hypervisor_GetVmInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hypervisor.proto",
}
