// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: proto/hypervisor/grpc/hypervisor.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Hypervisor_CreateVm_FullMethodName          = "/hypervisor.Hypervisor/CreateVm"
	Hypervisor_CreateVmStreaming_FullMethodName = "/hypervisor.Hypervisor/CreateVmStreaming"
	Hypervisor_StartVm_FullMethodName           = "/hypervisor.Hypervisor/StartVm"
	Hypervisor_DestroyVm_FullMethodName         = "/hypervisor.Hypervisor/DestroyVm"
	Hypervisor_ListVms_FullMethodName           = "/hypervisor.Hypervisor/ListVms"
	Hypervisor_GetVm_FullMethodName             = "/hypervisor.Hypervisor/GetVm"
)

// HypervisorClient is the client API for Hypervisor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Hypervisor service
type HypervisorClient interface {
	// CreateVm creates a VM asynchronously (non-blocking)
	// Returns immediately with VM in starting state
	// Client polls GetVm to check completion
	CreateVm(ctx context.Context, in *CreateVmRequest, opts ...grpc.CallOption) (*Vm, error)
	// CreateVmStreaming creates a VM with bidirectional streaming (blocking)
	// Client sends: initial request, then optionally streams image data
	// Server sends: multiple progress messages until VM is fully created
	CreateVmStreaming(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CreateVmStreamingRequest, CreateVmStreamingResponse], error)
	// StartVm starts a stopped VM
	StartVm(ctx context.Context, in *StartVmRequest, opts ...grpc.CallOption) (*Vm, error)
	// DestroyVm destroys a VM
	DestroyVm(ctx context.Context, in *DestroyVmRequest, opts ...grpc.CallOption) (*DestroyVmResponse, error)
	// ListVms lists all VMs on the hypervisor
	ListVms(ctx context.Context, in *ListVmsRequest, opts ...grpc.CallOption) (*ListVmsResponse, error)
	// GetVm gets information about a specific VM
	GetVm(ctx context.Context, in *GetVmRequest, opts ...grpc.CallOption) (*Vm, error)
}

type hypervisorClient struct {
	cc grpc.ClientConnInterface
}

func NewHypervisorClient(cc grpc.ClientConnInterface) HypervisorClient {
	return &hypervisorClient{cc}
}

func (c *hypervisorClient) CreateVm(ctx context.Context, in *CreateVmRequest, opts ...grpc.CallOption) (*Vm, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Vm)
	err := c.cc.Invoke(ctx, Hypervisor_CreateVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hypervisorClient) CreateVmStreaming(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CreateVmStreamingRequest, CreateVmStreamingResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Hypervisor_ServiceDesc.Streams[0], Hypervisor_CreateVmStreaming_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CreateVmStreamingRequest, CreateVmStreamingResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Hypervisor_CreateVmStreamingClient = grpc.BidiStreamingClient[CreateVmStreamingRequest, CreateVmStreamingResponse]

func (c *hypervisorClient) StartVm(ctx context.Context, in *StartVmRequest, opts ...grpc.CallOption) (*Vm, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Vm)
	err := c.cc.Invoke(ctx, Hypervisor_StartVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hypervisorClient) DestroyVm(ctx context.Context, in *DestroyVmRequest, opts ...grpc.CallOption) (*DestroyVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroyVmResponse)
	err := c.cc.Invoke(ctx, Hypervisor_DestroyVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hypervisorClient) ListVms(ctx context.Context, in *ListVmsRequest, opts ...grpc.CallOption) (*ListVmsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVmsResponse)
	err := c.cc.Invoke(ctx, Hypervisor_ListVms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hypervisorClient) GetVm(ctx context.Context, in *GetVmRequest, opts ...grpc.CallOption) (*Vm, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Vm)
	err := c.cc.Invoke(ctx, Hypervisor_GetVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HypervisorServer is the server API for Hypervisor service.
// All implementations should embed UnimplementedHypervisorServer
// for forward compatibility.
//
// Hypervisor service
type HypervisorServer interface {
	// CreateVm creates a VM asynchronously (non-blocking)
	// Returns immediately with VM in starting state
	// Client polls GetVm to check completion
	CreateVm(context.Context, *CreateVmRequest) (*Vm, error)
	// CreateVmStreaming creates a VM with bidirectional streaming (blocking)
	// Client sends: initial request, then optionally streams image data
	// Server sends: multiple progress messages until VM is fully created
	CreateVmStreaming(grpc.BidiStreamingServer[CreateVmStreamingRequest, CreateVmStreamingResponse]) error
	// StartVm starts a stopped VM
	StartVm(context.Context, *StartVmRequest) (*Vm, error)
	// DestroyVm destroys a VM
	DestroyVm(context.Context, *DestroyVmRequest) (*DestroyVmResponse, error)
	// ListVms lists all VMs on the hypervisor
	ListVms(context.Context, *ListVmsRequest) (*ListVmsResponse, error)
	// GetVm gets information about a specific VM
	GetVm(context.Context, *GetVmRequest) (*Vm, error)
}

// UnimplementedHypervisorServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHypervisorServer struct{}

func (UnimplementedHypervisorServer) CreateVm(context.Context, *CreateVmRequest) (*Vm, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVm not implemented")
}
func (UnimplementedHypervisorServer) CreateVmStreaming(grpc.BidiStreamingServer[CreateVmStreamingRequest, CreateVmStreamingResponse]) error {
	return status.Error(codes.Unimplemented, "method CreateVmStreaming not implemented")
}
func (UnimplementedHypervisorServer) StartVm(context.Context, *StartVmRequest) (*Vm, error) {
	return nil, status.Error(codes.Unimplemented, "method StartVm not implemented")
}
func (UnimplementedHypervisorServer) DestroyVm(context.Context, *DestroyVmRequest) (*DestroyVmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroyVm not implemented")
}
func (UnimplementedHypervisorServer) ListVms(context.Context, *ListVmsRequest) (*ListVmsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVms not implemented")
}
func (UnimplementedHypervisorServer) GetVm(context.Context, *GetVmRequest) (*Vm, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVm not implemented")
}
func (UnimplementedHypervisorServer) testEmbeddedByValue() {}

// UnsafeHypervisorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HypervisorServer will
// result in compilation errors.
type UnsafeHypervisorServer interface {
	mustEmbedUnimplementedHypervisorServer()
}

func RegisterHypervisorServer(s grpc.ServiceRegistrar, srv HypervisorServer) {
	// If the following call panics, it indicates UnimplementedHypervisorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Hypervisor_ServiceDesc, srv)
}

func _Hypervisor_CreateVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HypervisorServer).CreateVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hypervisor_CreateVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HypervisorServer).CreateVm(ctx, req.(*CreateVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hypervisor_CreateVmStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HypervisorServer).CreateVmStreaming(&grpc.GenericServerStream[CreateVmStreamingRequest, CreateVmStreamingResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Hypervisor_CreateVmStreamingServer = grpc.BidiStreamingServer[CreateVmStreamingRequest, CreateVmStreamingResponse]

func _Hypervisor_StartVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HypervisorServer).StartVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hypervisor_StartVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HypervisorServer).StartVm(ctx, req.(*StartVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hypervisor_DestroyVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HypervisorServer).DestroyVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hypervisor_DestroyVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HypervisorServer).DestroyVm(ctx, req.(*DestroyVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hypervisor_ListVms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVmsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HypervisorServer).ListVms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hypervisor_ListVms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HypervisorServer).ListVms(ctx, req.(*ListVmsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hypervisor_GetVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HypervisorServer).GetVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hypervisor_GetVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HypervisorServer).GetVm(ctx, req.(*GetVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Hypervisor_ServiceDesc is the grpc.ServiceDesc for Hypervisor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hypervisor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hypervisor.Hypervisor",
	HandlerType: (*HypervisorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVm",
			Handler:    _Hypervisor_CreateVm_Handler,
		},
		{
			MethodName: "StartVm",
			Handler:    _Hypervisor_StartVm_Handler,
		},
		{
			MethodName: "DestroyVm",
			Handler:    _Hypervisor_DestroyVm_Handler,
		},
		{
			MethodName: "ListVms",
			Handler:    _Hypervisor_ListVms_Handler,
		},
		{
			MethodName: "GetVm",
			Handler:    _Hypervisor_GetVm_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateVmStreaming",
			Handler:       _Hypervisor_CreateVmStreaming_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/hypervisor/grpc/hypervisor.proto",
}
