// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/hypervisor/grpc/hypervisor.proto

package grpc

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VmState represents the current state of a VM
type VmState int32

const (
	VmState_VM_STATE_UNSPECIFIED     VmState = 0
	VmState_VM_STATE_STARTING        VmState = 1
	VmState_VM_STATE_RUNNING         VmState = 2
	VmState_VM_STATE_FAILED_TO_START VmState = 3
	VmState_VM_STATE_STOPPING        VmState = 4
	VmState_VM_STATE_STOPPED         VmState = 5
	VmState_VM_STATE_MIGRATING       VmState = 6
	VmState_VM_STATE_EXPORTING       VmState = 7
	VmState_VM_STATE_CRASHED         VmState = 8
	VmState_VM_STATE_DESTROYING      VmState = 9
	VmState_VM_STATE_DEBUGGING       VmState = 10
)

// Enum value maps for VmState.
var (
	VmState_name = map[int32]string{
		0:  "VM_STATE_UNSPECIFIED",
		1:  "VM_STATE_STARTING",
		2:  "VM_STATE_RUNNING",
		3:  "VM_STATE_FAILED_TO_START",
		4:  "VM_STATE_STOPPING",
		5:  "VM_STATE_STOPPED",
		6:  "VM_STATE_MIGRATING",
		7:  "VM_STATE_EXPORTING",
		8:  "VM_STATE_CRASHED",
		9:  "VM_STATE_DESTROYING",
		10: "VM_STATE_DEBUGGING",
	}
	VmState_value = map[string]int32{
		"VM_STATE_UNSPECIFIED":     0,
		"VM_STATE_STARTING":        1,
		"VM_STATE_RUNNING":         2,
		"VM_STATE_FAILED_TO_START": 3,
		"VM_STATE_STOPPING":        4,
		"VM_STATE_STOPPED":         5,
		"VM_STATE_MIGRATING":       6,
		"VM_STATE_EXPORTING":       7,
		"VM_STATE_CRASHED":         8,
		"VM_STATE_DESTROYING":      9,
		"VM_STATE_DEBUGGING":       10,
	}
)

func (x VmState) Enum() *VmState {
	p := new(VmState)
	*p = x
	return p
}

func (x VmState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VmState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_hypervisor_grpc_hypervisor_proto_enumTypes[0].Descriptor()
}

func (VmState) Type() protoreflect.EnumType {
	return &file_proto_hypervisor_grpc_hypervisor_proto_enumTypes[0]
}

func (x VmState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VmState.Descriptor instead.
func (VmState) EnumDescriptor() ([]byte, []int) {
	return file_proto_hypervisor_grpc_hypervisor_proto_rawDescGZIP(), []int{0}
}

// VmView controls how much detail is returned for VM resources
// TODO: Can be extended with google.protobuf.FieldMask for fine-grained control
//
//	(REST: ?readMask=field1,field2)
type VmView int32

const (
	// Default view, same as BASIC
	VmView_VM_VIEW_UNSPECIFIED VmView = 0
	// Basic fields only: ip_address, hostname, state
	VmView_VM_VIEW_BASIC VmView = 1
	// All fields
	VmView_VM_VIEW_FULL VmView = 2
)

// Enum value maps for VmView.
var (
	VmView_name = map[int32]string{
		0: "VM_VIEW_UNSPECIFIED",
		1: "VM_VIEW_BASIC",
		2: "VM_VIEW_FULL",
	}
	VmView_value = map[string]int32{
		"VM_VIEW_UNSPECIFIED": 0,
		"VM_VIEW_BASIC":       1,
		"VM_VIEW_FULL":        2,
	}
)

func (x VmView) Enum() *VmView {
	p := new(VmView)
	*p = x
	return p
}

func (x VmView) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VmView) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_hypervisor_grpc_hypervisor_proto_enumTypes[1].Descriptor()
}

func (VmView) Type() protoreflect.EnumType {
	return &file_proto_hypervisor_grpc_hypervisor_proto_enumTypes[1]
}

func (x VmView) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VmView.Descriptor instead.
func (VmView) EnumDescriptor() ([]byte, []int) {
	return file_proto_hypervisor_grpc_hypervisor_proto_rawDescGZIP(), []int{1}
}

// Vm represents a virtual machine resource
type Vm struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output only. IP address assigned to the VM
	IpAddress string `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// Output only. Current state of the VM
	State VmState `protobuf:"varint,2,opt,name=state,proto3,enum=hypervisor.VmState" json:"state,omitempty"`
	// Required. VM hostname
	Hostname string `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Required. Memory allocation in MiB
	MemoryInMib uint32 `protobuf:"varint,4,opt,name=memory_in_mib,json=memoryInMib,proto3" json:"memory_in_mib,omitempty"`
	// Required. CPU allocation in milli-CPUs (1000 = 1 CPU)
	MilliCpus uint32 `protobuf:"varint,5,opt,name=milli_cpus,json=milliCpus,proto3" json:"milli_cpus,omitempty"`
	// Image name to fetch from image server
	ImageName string `protobuf:"bytes,6,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	// Input only. Image URL to fetch via HTTP
	ImageUrl string `protobuf:"bytes,7,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	// Additional owner users
	OwnerUsers []string `protobuf:"bytes,8,rep,name=owner_users,json=ownerUsers,proto3" json:"owner_users,omitempty"`
	// VM tags
	Tags map[string]string `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Input only. Don't start VM after creation
	DoNotStart    bool `protobuf:"varint,10,opt,name=do_not_start,json=doNotStart,proto3" json:"do_not_start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vm) Reset() {
	*x = Vm{}
	mi := &file_proto_hypervisor_grpc_hypervisor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vm) ProtoMessage() {}

func (x *Vm) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hypervisor_grpc_hypervisor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vm.ProtoReflect.Descriptor instead.
func (*Vm) Descriptor() ([]byte, []int) {
	return file_proto_hypervisor_grpc_hypervisor_proto_rawDescGZIP(), []int{0}
}

func (x *Vm) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Vm) GetState() VmState {
	if x != nil {
		return x.State
	}
	return VmState_VM_STATE_UNSPECIFIED
}

func (x *Vm) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Vm) GetMemoryInMib() uint32 {
	if x != nil {
		return x.MemoryInMib
	}
	return 0
}

func (x *Vm) GetMilliCpus() uint32 {
	if x != nil {
		return x.MilliCpus
	}
	return 0
}

func (x *Vm) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *Vm) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Vm) GetOwnerUsers() []string {
	if x != nil {
		return x.OwnerUsers
	}
	return nil
}

func (x *Vm) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Vm) GetDoNotStart() bool {
	if x != nil {
		return x.DoNotStart
	}
	return false
}

// CreateVmRequest for creating a VM
type CreateVmRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The VM to create
	Vm            *Vm `protobuf:"bytes,1,opt,name=vm,proto3" json:"vm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVmRequest) Reset() {
	*x = CreateVmRequest{}
	mi := &file_proto_hypervisor_grpc_hypervisor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVmRequest) ProtoMessage() {}

func (x *CreateVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hypervisor_grpc_hypervisor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVmRequest.ProtoReflect.Descriptor instead.
func (*CreateVmRequest) Descriptor() ([]byte, []int) {
	return file_proto_hypervisor_grpc_hypervisor_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVmRequest) GetVm() *Vm {
	if x != nil {
		return x.Vm
	}
	return nil
}

// StartVmRequest for starting a VM
type StartVmRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. IP address of the VM to start
	IpAddress     string `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVmRequest) Reset() {
	*x = StartVmRequest{}
	mi := &file_proto_hypervisor_grpc_hypervisor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVmRequest) ProtoMessage() {}

func (x *StartVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hypervisor_grpc_hypervisor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVmRequest.ProtoReflect.Descriptor instead.
func (*StartVmRequest) Descriptor() ([]byte, []int) {
	return file_proto_hypervisor_grpc_hypervisor_proto_rawDescGZIP(), []int{2}
}

func (x *StartVmRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

// DestroyVmRequest for destroying a VM
type DestroyVmRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. IP address of the VM to destroy
	IpAddress     string `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyVmRequest) Reset() {
	*x = DestroyVmRequest{}
	mi := &file_proto_hypervisor_grpc_hypervisor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyVmRequest) ProtoMessage() {}

func (x *DestroyVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hypervisor_grpc_hypervisor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyVmRequest.ProtoReflect.Descriptor instead.
func (*DestroyVmRequest) Descriptor() ([]byte, []int) {
	return file_proto_hypervisor_grpc_hypervisor_proto_rawDescGZIP(), []int{3}
}

func (x *DestroyVmRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

// DestroyVmResponse is empty on success
type DestroyVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyVmResponse) Reset() {
	*x = DestroyVmResponse{}
	mi := &file_proto_hypervisor_grpc_hypervisor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyVmResponse) ProtoMessage() {}

func (x *DestroyVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hypervisor_grpc_hypervisor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyVmResponse.ProtoReflect.Descriptor instead.
func (*DestroyVmResponse) Descriptor() ([]byte, []int) {
	return file_proto_hypervisor_grpc_hypervisor_proto_rawDescGZIP(), []int{4}
}

// ListVmsRequest for listing VMs
type ListVmsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Controls how much detail to return. Defaults to BASIC.
	// Note: VM_VIEW_FULL returns UNIMPLEMENTED until backend optimization is done.
	View          VmView `protobuf:"varint,1,opt,name=view,proto3,enum=hypervisor.VmView" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVmsRequest) Reset() {
	*x = ListVmsRequest{}
	mi := &file_proto_hypervisor_grpc_hypervisor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVmsRequest) ProtoMessage() {}

func (x *ListVmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hypervisor_grpc_hypervisor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVmsRequest.ProtoReflect.Descriptor instead.
func (*ListVmsRequest) Descriptor() ([]byte, []int) {
	return file_proto_hypervisor_grpc_hypervisor_proto_rawDescGZIP(), []int{5}
}

func (x *ListVmsRequest) GetView() VmView {
	if x != nil {
		return x.View
	}
	return VmView_VM_VIEW_UNSPECIFIED
}

// ListVmsResponse contains all VMs
type ListVmsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vms           []*Vm                  `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVmsResponse) Reset() {
	*x = ListVmsResponse{}
	mi := &file_proto_hypervisor_grpc_hypervisor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVmsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVmsResponse) ProtoMessage() {}

func (x *ListVmsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hypervisor_grpc_hypervisor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVmsResponse.ProtoReflect.Descriptor instead.
func (*ListVmsResponse) Descriptor() ([]byte, []int) {
	return file_proto_hypervisor_grpc_hypervisor_proto_rawDescGZIP(), []int{6}
}

func (x *ListVmsResponse) GetVms() []*Vm {
	if x != nil {
		return x.Vms
	}
	return nil
}

// GetVmRequest for getting a specific VM
type GetVmRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. IP address of the VM to get
	IpAddress string `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// Controls how much detail to return. Defaults to FULL for single VM.
	View          VmView `protobuf:"varint,2,opt,name=view,proto3,enum=hypervisor.VmView" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVmRequest) Reset() {
	*x = GetVmRequest{}
	mi := &file_proto_hypervisor_grpc_hypervisor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVmRequest) ProtoMessage() {}

func (x *GetVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hypervisor_grpc_hypervisor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVmRequest.ProtoReflect.Descriptor instead.
func (*GetVmRequest) Descriptor() ([]byte, []int) {
	return file_proto_hypervisor_grpc_hypervisor_proto_rawDescGZIP(), []int{7}
}

func (x *GetVmRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *GetVmRequest) GetView() VmView {
	if x != nil {
		return x.View
	}
	return VmView_VM_VIEW_UNSPECIFIED
}

// CreateVmStreaming - Synchronous VM creation with streaming progress
type CreateVmStreamingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*CreateVmStreamingRequest_Metadata
	//	*CreateVmStreamingRequest_ImageDataChunk
	Request       isCreateVmStreamingRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVmStreamingRequest) Reset() {
	*x = CreateVmStreamingRequest{}
	mi := &file_proto_hypervisor_grpc_hypervisor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVmStreamingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVmStreamingRequest) ProtoMessage() {}

func (x *CreateVmStreamingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hypervisor_grpc_hypervisor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVmStreamingRequest.ProtoReflect.Descriptor instead.
func (*CreateVmStreamingRequest) Descriptor() ([]byte, []int) {
	return file_proto_hypervisor_grpc_hypervisor_proto_rawDescGZIP(), []int{8}
}

func (x *CreateVmStreamingRequest) GetRequest() isCreateVmStreamingRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *CreateVmStreamingRequest) GetMetadata() *CreateVmStreamingMetadata {
	if x != nil {
		if x, ok := x.Request.(*CreateVmStreamingRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *CreateVmStreamingRequest) GetImageDataChunk() []byte {
	if x != nil {
		if x, ok := x.Request.(*CreateVmStreamingRequest_ImageDataChunk); ok {
			return x.ImageDataChunk
		}
	}
	return nil
}

type isCreateVmStreamingRequest_Request interface {
	isCreateVmStreamingRequest_Request()
}

type CreateVmStreamingRequest_Metadata struct {
	// First message: VM to create with optional streaming parameters
	Metadata *CreateVmStreamingMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type CreateVmStreamingRequest_ImageDataChunk struct {
	// Subsequent messages: Image data chunks
	ImageDataChunk []byte `protobuf:"bytes,2,opt,name=image_data_chunk,json=imageDataChunk,proto3,oneof"`
}

func (*CreateVmStreamingRequest_Metadata) isCreateVmStreamingRequest_Request() {}

func (*CreateVmStreamingRequest_ImageDataChunk) isCreateVmStreamingRequest_Request() {}

// CreateVmStreamingMetadata contains VM spec plus streaming parameters
type CreateVmStreamingMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The VM to create
	Vm *Vm `protobuf:"bytes,1,opt,name=vm,proto3" json:"vm,omitempty"`
	// Size of image data to stream (0 if using image_name or image_url)
	ImageDataSize uint64 `protobuf:"varint,2,opt,name=image_data_size,json=imageDataSize,proto3" json:"image_data_size,omitempty"`
	// DHCP timeout duration in nanoseconds
	DhcpTimeout int64 `protobuf:"varint,3,opt,name=dhcp_timeout,json=dhcpTimeout,proto3" json:"dhcp_timeout,omitempty"`
	// Size of user data to stream after image data
	UserDataSize  uint64 `protobuf:"varint,4,opt,name=user_data_size,json=userDataSize,proto3" json:"user_data_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVmStreamingMetadata) Reset() {
	*x = CreateVmStreamingMetadata{}
	mi := &file_proto_hypervisor_grpc_hypervisor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVmStreamingMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVmStreamingMetadata) ProtoMessage() {}

func (x *CreateVmStreamingMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hypervisor_grpc_hypervisor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVmStreamingMetadata.ProtoReflect.Descriptor instead.
func (*CreateVmStreamingMetadata) Descriptor() ([]byte, []int) {
	return file_proto_hypervisor_grpc_hypervisor_proto_rawDescGZIP(), []int{9}
}

func (x *CreateVmStreamingMetadata) GetVm() *Vm {
	if x != nil {
		return x.Vm
	}
	return nil
}

func (x *CreateVmStreamingMetadata) GetImageDataSize() uint64 {
	if x != nil {
		return x.ImageDataSize
	}
	return 0
}

func (x *CreateVmStreamingMetadata) GetDhcpTimeout() int64 {
	if x != nil {
		return x.DhcpTimeout
	}
	return 0
}

func (x *CreateVmStreamingMetadata) GetUserDataSize() uint64 {
	if x != nil {
		return x.UserDataSize
	}
	return 0
}

// CreateVmStreamingResponse contains progress or final result
type CreateVmStreamingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Progress message during creation
	ProgressMessage string `protobuf:"bytes,1,opt,name=progress_message,json=progressMessage,proto3" json:"progress_message,omitempty"`
	// The created VM (only set in final response)
	Vm *Vm `protobuf:"bytes,2,opt,name=vm,proto3" json:"vm,omitempty"`
	// Whether DHCP timed out
	DhcpTimedOut  bool `protobuf:"varint,3,opt,name=dhcp_timed_out,json=dhcpTimedOut,proto3" json:"dhcp_timed_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVmStreamingResponse) Reset() {
	*x = CreateVmStreamingResponse{}
	mi := &file_proto_hypervisor_grpc_hypervisor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVmStreamingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVmStreamingResponse) ProtoMessage() {}

func (x *CreateVmStreamingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hypervisor_grpc_hypervisor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVmStreamingResponse.ProtoReflect.Descriptor instead.
func (*CreateVmStreamingResponse) Descriptor() ([]byte, []int) {
	return file_proto_hypervisor_grpc_hypervisor_proto_rawDescGZIP(), []int{10}
}

func (x *CreateVmStreamingResponse) GetProgressMessage() string {
	if x != nil {
		return x.ProgressMessage
	}
	return ""
}

func (x *CreateVmStreamingResponse) GetVm() *Vm {
	if x != nil {
		return x.Vm
	}
	return nil
}

func (x *CreateVmStreamingResponse) GetDhcpTimedOut() bool {
	if x != nil {
		return x.DhcpTimedOut
	}
	return false
}

var File_proto_hypervisor_grpc_hypervisor_proto protoreflect.FileDescriptor

const file_proto_hypervisor_grpc_hypervisor_proto_rawDesc = "" +
	"\n" +
	"&proto/hypervisor/grpc/hypervisor.proto\x12\n" +
	"hypervisor\x1a\x1cgoogle/api/annotations.proto\"\x93\x03\n" +
	"\x02Vm\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress\x12)\n" +
	"\x05state\x18\x02 \x01(\x0e2\x13.hypervisor.VmStateR\x05state\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\"\n" +
	"\rmemory_in_mib\x18\x04 \x01(\rR\vmemoryInMib\x12\x1d\n" +
	"\n" +
	"milli_cpus\x18\x05 \x01(\rR\tmilliCpus\x12\x1d\n" +
	"\n" +
	"image_name\x18\x06 \x01(\tR\timageName\x12\x1b\n" +
	"\timage_url\x18\a \x01(\tR\bimageUrl\x12\x1f\n" +
	"\vowner_users\x18\b \x03(\tR\n" +
	"ownerUsers\x12,\n" +
	"\x04tags\x18\t \x03(\v2\x18.hypervisor.Vm.TagsEntryR\x04tags\x12 \n" +
	"\fdo_not_start\x18\n" +
	" \x01(\bR\n" +
	"doNotStart\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"1\n" +
	"\x0fCreateVmRequest\x12\x1e\n" +
	"\x02vm\x18\x01 \x01(\v2\x0e.hypervisor.VmR\x02vm\"/\n" +
	"\x0eStartVmRequest\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress\"1\n" +
	"\x10DestroyVmRequest\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress\"\x13\n" +
	"\x11DestroyVmResponse\"8\n" +
	"\x0eListVmsRequest\x12&\n" +
	"\x04view\x18\x01 \x01(\x0e2\x12.hypervisor.VmViewR\x04view\"3\n" +
	"\x0fListVmsResponse\x12 \n" +
	"\x03vms\x18\x01 \x03(\v2\x0e.hypervisor.VmR\x03vms\"U\n" +
	"\fGetVmRequest\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress\x12&\n" +
	"\x04view\x18\x02 \x01(\x0e2\x12.hypervisor.VmViewR\x04view\"\x96\x01\n" +
	"\x18CreateVmStreamingRequest\x12C\n" +
	"\bmetadata\x18\x01 \x01(\v2%.hypervisor.CreateVmStreamingMetadataH\x00R\bmetadata\x12*\n" +
	"\x10image_data_chunk\x18\x02 \x01(\fH\x00R\x0eimageDataChunkB\t\n" +
	"\arequest\"\xac\x01\n" +
	"\x19CreateVmStreamingMetadata\x12\x1e\n" +
	"\x02vm\x18\x01 \x01(\v2\x0e.hypervisor.VmR\x02vm\x12&\n" +
	"\x0fimage_data_size\x18\x02 \x01(\x04R\rimageDataSize\x12!\n" +
	"\fdhcp_timeout\x18\x03 \x01(\x03R\vdhcpTimeout\x12$\n" +
	"\x0euser_data_size\x18\x04 \x01(\x04R\fuserDataSize\"\x8c\x01\n" +
	"\x19CreateVmStreamingResponse\x12)\n" +
	"\x10progress_message\x18\x01 \x01(\tR\x0fprogressMessage\x12\x1e\n" +
	"\x02vm\x18\x02 \x01(\v2\x0e.hypervisor.VmR\x02vm\x12$\n" +
	"\x0edhcp_timed_out\x18\x03 \x01(\bR\fdhcpTimedOut*\x92\x02\n" +
	"\aVmState\x12\x18\n" +
	"\x14VM_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11VM_STATE_STARTING\x10\x01\x12\x14\n" +
	"\x10VM_STATE_RUNNING\x10\x02\x12\x1c\n" +
	"\x18VM_STATE_FAILED_TO_START\x10\x03\x12\x15\n" +
	"\x11VM_STATE_STOPPING\x10\x04\x12\x14\n" +
	"\x10VM_STATE_STOPPED\x10\x05\x12\x16\n" +
	"\x12VM_STATE_MIGRATING\x10\x06\x12\x16\n" +
	"\x12VM_STATE_EXPORTING\x10\a\x12\x14\n" +
	"\x10VM_STATE_CRASHED\x10\b\x12\x17\n" +
	"\x13VM_STATE_DESTROYING\x10\t\x12\x16\n" +
	"\x12VM_STATE_DEBUGGING\x10\n" +
	"*F\n" +
	"\x06VmView\x12\x17\n" +
	"\x13VM_VIEW_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rVM_VIEW_BASIC\x10\x01\x12\x10\n" +
	"\fVM_VIEW_FULL\x10\x022\xa9\x04\n" +
	"\n" +
	"Hypervisor\x12L\n" +
	"\bCreateVm\x12\x1b.hypervisor.CreateVmRequest\x1a\x0e.hypervisor.Vm\"\x13\x82\xd3\xe4\x93\x02\r:\x02vm\"\a/v1/vms\x12d\n" +
	"\x11CreateVmStreaming\x12$.hypervisor.CreateVmStreamingRequest\x1a%.hypervisor.CreateVmStreamingResponse(\x010\x01\x12Y\n" +
	"\aStartVm\x12\x1a.hypervisor.StartVmRequest\x1a\x0e.hypervisor.Vm\"\"\x82\xd3\xe4\x93\x02\x1c\"\x1a/v1/vms/{ip_address}:start\x12f\n" +
	"\tDestroyVm\x12\x1c.hypervisor.DestroyVmRequest\x1a\x1d.hypervisor.DestroyVmResponse\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/v1/vms/{ip_address}\x12S\n" +
	"\aListVms\x12\x1a.hypervisor.ListVmsRequest\x1a\x1b.hypervisor.ListVmsResponse\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/v1/vms\x12O\n" +
	"\x05GetVm\x12\x18.hypervisor.GetVmRequest\x1a\x0e.hypervisor.Vm\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/vms/{ip_address}B>Z<github.com/Cloud-Foundations/Dominator/proto/hypervisor/grpcb\x06proto3"

var (
	file_proto_hypervisor_grpc_hypervisor_proto_rawDescOnce sync.Once
	file_proto_hypervisor_grpc_hypervisor_proto_rawDescData []byte
)

func file_proto_hypervisor_grpc_hypervisor_proto_rawDescGZIP() []byte {
	file_proto_hypervisor_grpc_hypervisor_proto_rawDescOnce.Do(func() {
		file_proto_hypervisor_grpc_hypervisor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hypervisor_grpc_hypervisor_proto_rawDesc), len(file_proto_hypervisor_grpc_hypervisor_proto_rawDesc)))
	})
	return file_proto_hypervisor_grpc_hypervisor_proto_rawDescData
}

var file_proto_hypervisor_grpc_hypervisor_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_hypervisor_grpc_hypervisor_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_hypervisor_grpc_hypervisor_proto_goTypes = []any{
	(VmState)(0),                      // 0: hypervisor.VmState
	(VmView)(0),                       // 1: hypervisor.VmView
	(*Vm)(nil),                        // 2: hypervisor.Vm
	(*CreateVmRequest)(nil),           // 3: hypervisor.CreateVmRequest
	(*StartVmRequest)(nil),            // 4: hypervisor.StartVmRequest
	(*DestroyVmRequest)(nil),          // 5: hypervisor.DestroyVmRequest
	(*DestroyVmResponse)(nil),         // 6: hypervisor.DestroyVmResponse
	(*ListVmsRequest)(nil),            // 7: hypervisor.ListVmsRequest
	(*ListVmsResponse)(nil),           // 8: hypervisor.ListVmsResponse
	(*GetVmRequest)(nil),              // 9: hypervisor.GetVmRequest
	(*CreateVmStreamingRequest)(nil),  // 10: hypervisor.CreateVmStreamingRequest
	(*CreateVmStreamingMetadata)(nil), // 11: hypervisor.CreateVmStreamingMetadata
	(*CreateVmStreamingResponse)(nil), // 12: hypervisor.CreateVmStreamingResponse
	nil,                               // 13: hypervisor.Vm.TagsEntry
}
var file_proto_hypervisor_grpc_hypervisor_proto_depIdxs = []int32{
	0,  // 0: hypervisor.Vm.state:type_name -> hypervisor.VmState
	13, // 1: hypervisor.Vm.tags:type_name -> hypervisor.Vm.TagsEntry
	2,  // 2: hypervisor.CreateVmRequest.vm:type_name -> hypervisor.Vm
	1,  // 3: hypervisor.ListVmsRequest.view:type_name -> hypervisor.VmView
	2,  // 4: hypervisor.ListVmsResponse.vms:type_name -> hypervisor.Vm
	1,  // 5: hypervisor.GetVmRequest.view:type_name -> hypervisor.VmView
	11, // 6: hypervisor.CreateVmStreamingRequest.metadata:type_name -> hypervisor.CreateVmStreamingMetadata
	2,  // 7: hypervisor.CreateVmStreamingMetadata.vm:type_name -> hypervisor.Vm
	2,  // 8: hypervisor.CreateVmStreamingResponse.vm:type_name -> hypervisor.Vm
	3,  // 9: hypervisor.Hypervisor.CreateVm:input_type -> hypervisor.CreateVmRequest
	10, // 10: hypervisor.Hypervisor.CreateVmStreaming:input_type -> hypervisor.CreateVmStreamingRequest
	4,  // 11: hypervisor.Hypervisor.StartVm:input_type -> hypervisor.StartVmRequest
	5,  // 12: hypervisor.Hypervisor.DestroyVm:input_type -> hypervisor.DestroyVmRequest
	7,  // 13: hypervisor.Hypervisor.ListVms:input_type -> hypervisor.ListVmsRequest
	9,  // 14: hypervisor.Hypervisor.GetVm:input_type -> hypervisor.GetVmRequest
	2,  // 15: hypervisor.Hypervisor.CreateVm:output_type -> hypervisor.Vm
	12, // 16: hypervisor.Hypervisor.CreateVmStreaming:output_type -> hypervisor.CreateVmStreamingResponse
	2,  // 17: hypervisor.Hypervisor.StartVm:output_type -> hypervisor.Vm
	6,  // 18: hypervisor.Hypervisor.DestroyVm:output_type -> hypervisor.DestroyVmResponse
	8,  // 19: hypervisor.Hypervisor.ListVms:output_type -> hypervisor.ListVmsResponse
	2,  // 20: hypervisor.Hypervisor.GetVm:output_type -> hypervisor.Vm
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_hypervisor_grpc_hypervisor_proto_init() }
func file_proto_hypervisor_grpc_hypervisor_proto_init() {
	if File_proto_hypervisor_grpc_hypervisor_proto != nil {
		return
	}
	file_proto_hypervisor_grpc_hypervisor_proto_msgTypes[8].OneofWrappers = []any{
		(*CreateVmStreamingRequest_Metadata)(nil),
		(*CreateVmStreamingRequest_ImageDataChunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hypervisor_grpc_hypervisor_proto_rawDesc), len(file_proto_hypervisor_grpc_hypervisor_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hypervisor_grpc_hypervisor_proto_goTypes,
		DependencyIndexes: file_proto_hypervisor_grpc_hypervisor_proto_depIdxs,
		EnumInfos:         file_proto_hypervisor_grpc_hypervisor_proto_enumTypes,
		MessageInfos:      file_proto_hypervisor_grpc_hypervisor_proto_msgTypes,
	}.Build()
	File_proto_hypervisor_grpc_hypervisor_proto = out.File
	file_proto_hypervisor_grpc_hypervisor_proto_goTypes = nil
	file_proto_hypervisor_grpc_hypervisor_proto_depIdxs = nil
}
