// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: fleetmanager/grpc/fleetmanager.proto

package grpc

import (
	grpc "github.com/Cloud-Foundations/Dominator/proto/common/grpc"
	grpc1 "github.com/Cloud-Foundations/Dominator/proto/hypervisor/grpc"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChangeMachineTags
type ChangeMachineTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Tags          *grpc.Tags             `protobuf:"bytes,2,opt,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeMachineTagsRequest) Reset() {
	*x = ChangeMachineTagsRequest{}
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeMachineTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeMachineTagsRequest) ProtoMessage() {}

func (x *ChangeMachineTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeMachineTagsRequest.ProtoReflect.Descriptor instead.
func (*ChangeMachineTagsRequest) Descriptor() ([]byte, []int) {
	return file_fleetmanager_grpc_fleetmanager_proto_rawDescGZIP(), []int{0}
}

func (x *ChangeMachineTagsRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ChangeMachineTagsRequest) GetTags() *grpc.Tags {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ChangeMachineTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeMachineTagsResponse) Reset() {
	*x = ChangeMachineTagsResponse{}
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeMachineTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeMachineTagsResponse) ProtoMessage() {}

func (x *ChangeMachineTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeMachineTagsResponse.ProtoReflect.Descriptor instead.
func (*ChangeMachineTagsResponse) Descriptor() ([]byte, []int) {
	return file_fleetmanager_grpc_fleetmanager_proto_rawDescGZIP(), []int{1}
}

// GetMachineInfo
type GetMachineInfoRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Hostname               string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IgnoreMissingLocalTags bool                   `protobuf:"varint,2,opt,name=ignore_missing_local_tags,json=ignoreMissingLocalTags,proto3" json:"ignore_missing_local_tags,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetMachineInfoRequest) Reset() {
	*x = GetMachineInfoRequest{}
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMachineInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMachineInfoRequest) ProtoMessage() {}

func (x *GetMachineInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMachineInfoRequest.ProtoReflect.Descriptor instead.
func (*GetMachineInfoRequest) Descriptor() ([]byte, []int) {
	return file_fleetmanager_grpc_fleetmanager_proto_rawDescGZIP(), []int{2}
}

func (x *GetMachineInfoRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *GetMachineInfoRequest) GetIgnoreMissingLocalTags() bool {
	if x != nil {
		return x.IgnoreMissingLocalTags
	}
	return false
}

type GetMachineInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Machine       *Machine               `protobuf:"bytes,2,opt,name=machine,proto3" json:"machine,omitempty"`
	Subnets       []*grpc1.Subnet        `protobuf:"bytes,3,rep,name=subnets,proto3" json:"subnets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMachineInfoResponse) Reset() {
	*x = GetMachineInfoResponse{}
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMachineInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMachineInfoResponse) ProtoMessage() {}

func (x *GetMachineInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMachineInfoResponse.ProtoReflect.Descriptor instead.
func (*GetMachineInfoResponse) Descriptor() ([]byte, []int) {
	return file_fleetmanager_grpc_fleetmanager_proto_rawDescGZIP(), []int{3}
}

func (x *GetMachineInfoResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *GetMachineInfoResponse) GetMachine() *Machine {
	if x != nil {
		return x.Machine
	}
	return nil
}

func (x *GetMachineInfoResponse) GetSubnets() []*grpc1.Subnet {
	if x != nil {
		return x.Subnets
	}
	return nil
}

// GetHypervisorForVM
type GetHypervisorForVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpAddress     []byte                 `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"` // net.IP is []byte
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHypervisorForVMRequest) Reset() {
	*x = GetHypervisorForVMRequest{}
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHypervisorForVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHypervisorForVMRequest) ProtoMessage() {}

func (x *GetHypervisorForVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHypervisorForVMRequest.ProtoReflect.Descriptor instead.
func (*GetHypervisorForVMRequest) Descriptor() ([]byte, []int) {
	return file_fleetmanager_grpc_fleetmanager_proto_rawDescGZIP(), []int{4}
}

func (x *GetHypervisorForVMRequest) GetIpAddress() []byte {
	if x != nil {
		return x.IpAddress
	}
	return nil
}

type GetHypervisorForVMResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HypervisorAddress string                 `protobuf:"bytes,1,opt,name=hypervisor_address,json=hypervisorAddress,proto3" json:"hypervisor_address,omitempty"` // host:port
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetHypervisorForVMResponse) Reset() {
	*x = GetHypervisorForVMResponse{}
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHypervisorForVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHypervisorForVMResponse) ProtoMessage() {}

func (x *GetHypervisorForVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHypervisorForVMResponse.ProtoReflect.Descriptor instead.
func (*GetHypervisorForVMResponse) Descriptor() ([]byte, []int) {
	return file_fleetmanager_grpc_fleetmanager_proto_rawDescGZIP(), []int{5}
}

func (x *GetHypervisorForVMResponse) GetHypervisorAddress() string {
	if x != nil {
		return x.HypervisorAddress
	}
	return ""
}

// ListHypervisorLocations
type ListHypervisorLocationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopLocation   string                 `protobuf:"bytes,1,opt,name=top_location,json=topLocation,proto3" json:"top_location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHypervisorLocationsRequest) Reset() {
	*x = ListHypervisorLocationsRequest{}
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHypervisorLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHypervisorLocationsRequest) ProtoMessage() {}

func (x *ListHypervisorLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHypervisorLocationsRequest.ProtoReflect.Descriptor instead.
func (*ListHypervisorLocationsRequest) Descriptor() ([]byte, []int) {
	return file_fleetmanager_grpc_fleetmanager_proto_rawDescGZIP(), []int{6}
}

func (x *ListHypervisorLocationsRequest) GetTopLocation() string {
	if x != nil {
		return x.TopLocation
	}
	return ""
}

type ListHypervisorLocationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []string               `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHypervisorLocationsResponse) Reset() {
	*x = ListHypervisorLocationsResponse{}
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHypervisorLocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHypervisorLocationsResponse) ProtoMessage() {}

func (x *ListHypervisorLocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHypervisorLocationsResponse.ProtoReflect.Descriptor instead.
func (*ListHypervisorLocationsResponse) Descriptor() ([]byte, []int) {
	return file_fleetmanager_grpc_fleetmanager_proto_rawDescGZIP(), []int{7}
}

func (x *ListHypervisorLocationsResponse) GetLocations() []string {
	if x != nil {
		return x.Locations
	}
	return nil
}

// ListHypervisorsInLocation
type ListHypervisorsInLocationRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	HypervisorTagsToMatch *grpc.MatchTags        `protobuf:"bytes,1,opt,name=hypervisor_tags_to_match,json=hypervisorTagsToMatch,proto3" json:"hypervisor_tags_to_match,omitempty"`
	IncludeUnhealthy      bool                   `protobuf:"varint,2,opt,name=include_unhealthy,json=includeUnhealthy,proto3" json:"include_unhealthy,omitempty"`
	Location              string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	SubnetId              string                 `protobuf:"bytes,4,opt,name=subnet_id,json=subnetId,proto3" json:"subnet_id,omitempty"`
	TagsToInclude         []string               `protobuf:"bytes,5,rep,name=tags_to_include,json=tagsToInclude,proto3" json:"tags_to_include,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ListHypervisorsInLocationRequest) Reset() {
	*x = ListHypervisorsInLocationRequest{}
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHypervisorsInLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHypervisorsInLocationRequest) ProtoMessage() {}

func (x *ListHypervisorsInLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHypervisorsInLocationRequest.ProtoReflect.Descriptor instead.
func (*ListHypervisorsInLocationRequest) Descriptor() ([]byte, []int) {
	return file_fleetmanager_grpc_fleetmanager_proto_rawDescGZIP(), []int{8}
}

func (x *ListHypervisorsInLocationRequest) GetHypervisorTagsToMatch() *grpc.MatchTags {
	if x != nil {
		return x.HypervisorTagsToMatch
	}
	return nil
}

func (x *ListHypervisorsInLocationRequest) GetIncludeUnhealthy() bool {
	if x != nil {
		return x.IncludeUnhealthy
	}
	return false
}

func (x *ListHypervisorsInLocationRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ListHypervisorsInLocationRequest) GetSubnetId() string {
	if x != nil {
		return x.SubnetId
	}
	return ""
}

func (x *ListHypervisorsInLocationRequest) GetTagsToInclude() []string {
	if x != nil {
		return x.TagsToInclude
	}
	return nil
}

type ListHypervisorsInLocationResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	HypervisorAddresses []string               `protobuf:"bytes,1,rep,name=hypervisor_addresses,json=hypervisorAddresses,proto3" json:"hypervisor_addresses,omitempty"` // host:port
	TagsForHypervisors  []*grpc.Tags           `protobuf:"bytes,2,rep,name=tags_for_hypervisors,json=tagsForHypervisors,proto3" json:"tags_for_hypervisors,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListHypervisorsInLocationResponse) Reset() {
	*x = ListHypervisorsInLocationResponse{}
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHypervisorsInLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHypervisorsInLocationResponse) ProtoMessage() {}

func (x *ListHypervisorsInLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHypervisorsInLocationResponse.ProtoReflect.Descriptor instead.
func (*ListHypervisorsInLocationResponse) Descriptor() ([]byte, []int) {
	return file_fleetmanager_grpc_fleetmanager_proto_rawDescGZIP(), []int{9}
}

func (x *ListHypervisorsInLocationResponse) GetHypervisorAddresses() []string {
	if x != nil {
		return x.HypervisorAddresses
	}
	return nil
}

func (x *ListHypervisorsInLocationResponse) GetTagsForHypervisors() []*grpc.Tags {
	if x != nil {
		return x.TagsForHypervisors
	}
	return nil
}

// GetUpdates (streaming)
// Standard gRPC watch pattern - client controls stream lifetime via context cancellation
type GetUpdatesRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	IgnoreMissingLocalTags bool                   `protobuf:"varint,1,opt,name=ignore_missing_local_tags,json=ignoreMissingLocalTags,proto3" json:"ignore_missing_local_tags,omitempty"`
	Location               string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetUpdatesRequest) Reset() {
	*x = GetUpdatesRequest{}
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpdatesRequest) ProtoMessage() {}

func (x *GetUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpdatesRequest.ProtoReflect.Descriptor instead.
func (*GetUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_fleetmanager_grpc_fleetmanager_proto_rawDescGZIP(), []int{10}
}

func (x *GetUpdatesRequest) GetIgnoreMissingLocalTags() bool {
	if x != nil {
		return x.IgnoreMissingLocalTags
	}
	return false
}

func (x *GetUpdatesRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type Update struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	ChangedMachines []*Machine               `protobuf:"bytes,1,rep,name=changed_machines,json=changedMachines,proto3" json:"changed_machines,omitempty"`
	ChangedVms      map[string]*grpc1.VmInfo `protobuf:"bytes,2,rep,name=changed_vms,json=changedVms,proto3" json:"changed_vms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`               // Key: IP address
	DeletedMachines []string                 `protobuf:"bytes,3,rep,name=deleted_machines,json=deletedMachines,proto3" json:"deleted_machines,omitempty"`                                                                          // Hostname
	DeletedVms      []string                 `protobuf:"bytes,4,rep,name=deleted_vms,json=deletedVms,proto3" json:"deleted_vms,omitempty"`                                                                                         // IP address
	VmToHypervisor  map[string]string        `protobuf:"bytes,5,rep,name=vm_to_hypervisor,json=vmToHypervisor,proto3" json:"vm_to_hypervisor,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // IP:hostname
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Update) Reset() {
	*x = Update{}
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_fleetmanager_grpc_fleetmanager_proto_rawDescGZIP(), []int{11}
}

func (x *Update) GetChangedMachines() []*Machine {
	if x != nil {
		return x.ChangedMachines
	}
	return nil
}

func (x *Update) GetChangedVms() map[string]*grpc1.VmInfo {
	if x != nil {
		return x.ChangedVms
	}
	return nil
}

func (x *Update) GetDeletedMachines() []string {
	if x != nil {
		return x.DeletedMachines
	}
	return nil
}

func (x *Update) GetDeletedVms() []string {
	if x != nil {
		return x.DeletedVms
	}
	return nil
}

func (x *Update) GetVmToHypervisor() map[string]string {
	if x != nil {
		return x.VmToHypervisor
	}
	return nil
}

// ListVMsInLocation (with pagination support)
type ListVMsInLocationRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	HypervisorTagsToMatch *grpc.MatchTags        `protobuf:"bytes,1,opt,name=hypervisor_tags_to_match,json=hypervisorTagsToMatch,proto3" json:"hypervisor_tags_to_match,omitempty"`
	Location              string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	OwnerGroups           []string               `protobuf:"bytes,3,rep,name=owner_groups,json=ownerGroups,proto3" json:"owner_groups,omitempty"`
	OwnerUsers            []string               `protobuf:"bytes,4,rep,name=owner_users,json=ownerUsers,proto3" json:"owner_users,omitempty"`
	VmTagsToMatch         *grpc.MatchTags        `protobuf:"bytes,5,opt,name=vm_tags_to_match,json=vmTagsToMatch,proto3" json:"vm_tags_to_match,omitempty"`
	// Pagination support (optional)
	PageSize      int32  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`   // 0 or omitted = return all VMs
	PageToken     string `protobuf:"bytes,7,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // Token for fetching next page
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVMsInLocationRequest) Reset() {
	*x = ListVMsInLocationRequest{}
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVMsInLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVMsInLocationRequest) ProtoMessage() {}

func (x *ListVMsInLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVMsInLocationRequest.ProtoReflect.Descriptor instead.
func (*ListVMsInLocationRequest) Descriptor() ([]byte, []int) {
	return file_fleetmanager_grpc_fleetmanager_proto_rawDescGZIP(), []int{12}
}

func (x *ListVMsInLocationRequest) GetHypervisorTagsToMatch() *grpc.MatchTags {
	if x != nil {
		return x.HypervisorTagsToMatch
	}
	return nil
}

func (x *ListVMsInLocationRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ListVMsInLocationRequest) GetOwnerGroups() []string {
	if x != nil {
		return x.OwnerGroups
	}
	return nil
}

func (x *ListVMsInLocationRequest) GetOwnerUsers() []string {
	if x != nil {
		return x.OwnerUsers
	}
	return nil
}

func (x *ListVMsInLocationRequest) GetVmTagsToMatch() *grpc.MatchTags {
	if x != nil {
		return x.VmTagsToMatch
	}
	return nil
}

func (x *ListVMsInLocationRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListVMsInLocationRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListVMsInLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpAddresses   [][]byte               `protobuf:"bytes,1,rep,name=ip_addresses,json=ipAddresses,proto3" json:"ip_addresses,omitempty"`         // net.IP is []byte
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"` // Empty = no more results
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVMsInLocationResponse) Reset() {
	*x = ListVMsInLocationResponse{}
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVMsInLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVMsInLocationResponse) ProtoMessage() {}

func (x *ListVMsInLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVMsInLocationResponse.ProtoReflect.Descriptor instead.
func (*ListVMsInLocationResponse) Descriptor() ([]byte, []int) {
	return file_fleetmanager_grpc_fleetmanager_proto_rawDescGZIP(), []int{13}
}

func (x *ListVMsInLocationResponse) GetIpAddresses() [][]byte {
	if x != nil {
		return x.IpAddresses
	}
	return nil
}

func (x *ListVMsInLocationResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// PowerOnMachine
type PowerOnMachineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PowerOnMachineRequest) Reset() {
	*x = PowerOnMachineRequest{}
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerOnMachineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerOnMachineRequest) ProtoMessage() {}

func (x *PowerOnMachineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerOnMachineRequest.ProtoReflect.Descriptor instead.
func (*PowerOnMachineRequest) Descriptor() ([]byte, []int) {
	return file_fleetmanager_grpc_fleetmanager_proto_rawDescGZIP(), []int{14}
}

func (x *PowerOnMachineRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type PowerOnMachineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PowerOnMachineResponse) Reset() {
	*x = PowerOnMachineResponse{}
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerOnMachineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerOnMachineResponse) ProtoMessage() {}

func (x *PowerOnMachineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerOnMachineResponse.ProtoReflect.Descriptor instead.
func (*PowerOnMachineResponse) Descriptor() ([]byte, []int) {
	return file_fleetmanager_grpc_fleetmanager_proto_rawDescGZIP(), []int{15}
}

// GetHypervisorsInLocation
type GetHypervisorsInLocationRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	HypervisorTagsToMatch *grpc.MatchTags        `protobuf:"bytes,1,opt,name=hypervisor_tags_to_match,json=hypervisorTagsToMatch,proto3" json:"hypervisor_tags_to_match,omitempty"`
	IncludeUnhealthy      bool                   `protobuf:"varint,2,opt,name=include_unhealthy,json=includeUnhealthy,proto3" json:"include_unhealthy,omitempty"`
	IncludeVms            bool                   `protobuf:"varint,3,opt,name=include_vms,json=includeVms,proto3" json:"include_vms,omitempty"`
	Location              string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	SubnetId              string                 `protobuf:"bytes,5,opt,name=subnet_id,json=subnetId,proto3" json:"subnet_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetHypervisorsInLocationRequest) Reset() {
	*x = GetHypervisorsInLocationRequest{}
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHypervisorsInLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHypervisorsInLocationRequest) ProtoMessage() {}

func (x *GetHypervisorsInLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHypervisorsInLocationRequest.ProtoReflect.Descriptor instead.
func (*GetHypervisorsInLocationRequest) Descriptor() ([]byte, []int) {
	return file_fleetmanager_grpc_fleetmanager_proto_rawDescGZIP(), []int{16}
}

func (x *GetHypervisorsInLocationRequest) GetHypervisorTagsToMatch() *grpc.MatchTags {
	if x != nil {
		return x.HypervisorTagsToMatch
	}
	return nil
}

func (x *GetHypervisorsInLocationRequest) GetIncludeUnhealthy() bool {
	if x != nil {
		return x.IncludeUnhealthy
	}
	return false
}

func (x *GetHypervisorsInLocationRequest) GetIncludeVms() bool {
	if x != nil {
		return x.IncludeVms
	}
	return false
}

func (x *GetHypervisorsInLocationRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *GetHypervisorsInLocationRequest) GetSubnetId() string {
	if x != nil {
		return x.SubnetId
	}
	return ""
}

type GetHypervisorsInLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hypervisors   []*Hypervisor          `protobuf:"bytes,1,rep,name=hypervisors,proto3" json:"hypervisors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHypervisorsInLocationResponse) Reset() {
	*x = GetHypervisorsInLocationResponse{}
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHypervisorsInLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHypervisorsInLocationResponse) ProtoMessage() {}

func (x *GetHypervisorsInLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHypervisorsInLocationResponse.ProtoReflect.Descriptor instead.
func (*GetHypervisorsInLocationResponse) Descriptor() ([]byte, []int) {
	return file_fleetmanager_grpc_fleetmanager_proto_rawDescGZIP(), []int{17}
}

func (x *GetHypervisorsInLocationResponse) GetHypervisors() []*Hypervisor {
	if x != nil {
		return x.Hypervisors
	}
	return nil
}

// GetIpInfo
type GetIpInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpAddress     []byte                 `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"` // net.IP is []byte
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIpInfoRequest) Reset() {
	*x = GetIpInfoRequest{}
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIpInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIpInfoRequest) ProtoMessage() {}

func (x *GetIpInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIpInfoRequest.ProtoReflect.Descriptor instead.
func (*GetIpInfoRequest) Descriptor() ([]byte, []int) {
	return file_fleetmanager_grpc_fleetmanager_proto_rawDescGZIP(), []int{18}
}

func (x *GetIpInfoRequest) GetIpAddress() []byte {
	if x != nil {
		return x.IpAddress
	}
	return nil
}

type GetIpInfoResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HypervisorAddress string                 `protobuf:"bytes,1,opt,name=hypervisor_address,json=hypervisorAddress,proto3" json:"hypervisor_address,omitempty"` // host:port
	Vm                *grpc1.VmInfo          `protobuf:"bytes,2,opt,name=vm,proto3" json:"vm,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetIpInfoResponse) Reset() {
	*x = GetIpInfoResponse{}
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIpInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIpInfoResponse) ProtoMessage() {}

func (x *GetIpInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIpInfoResponse.ProtoReflect.Descriptor instead.
func (*GetIpInfoResponse) Descriptor() ([]byte, []int) {
	return file_fleetmanager_grpc_fleetmanager_proto_rawDescGZIP(), []int{19}
}

func (x *GetIpInfoResponse) GetHypervisorAddress() string {
	if x != nil {
		return x.HypervisorAddress
	}
	return ""
}

func (x *GetIpInfoResponse) GetVm() *grpc1.VmInfo {
	if x != nil {
		return x.Vm
	}
	return nil
}

// MoveIpAddresses
type MoveIpAddressesRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	HypervisorHostname string                 `protobuf:"bytes,1,opt,name=hypervisor_hostname,json=hypervisorHostname,proto3" json:"hypervisor_hostname,omitempty"`
	IpAddresses        [][]byte               `protobuf:"bytes,2,rep,name=ip_addresses,json=ipAddresses,proto3" json:"ip_addresses,omitempty"` // net.IP is []byte
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MoveIpAddressesRequest) Reset() {
	*x = MoveIpAddressesRequest{}
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveIpAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveIpAddressesRequest) ProtoMessage() {}

func (x *MoveIpAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveIpAddressesRequest.ProtoReflect.Descriptor instead.
func (*MoveIpAddressesRequest) Descriptor() ([]byte, []int) {
	return file_fleetmanager_grpc_fleetmanager_proto_rawDescGZIP(), []int{20}
}

func (x *MoveIpAddressesRequest) GetHypervisorHostname() string {
	if x != nil {
		return x.HypervisorHostname
	}
	return ""
}

func (x *MoveIpAddressesRequest) GetIpAddresses() [][]byte {
	if x != nil {
		return x.IpAddresses
	}
	return nil
}

type MoveIpAddressesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveIpAddressesResponse) Reset() {
	*x = MoveIpAddressesResponse{}
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveIpAddressesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveIpAddressesResponse) ProtoMessage() {}

func (x *MoveIpAddressesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveIpAddressesResponse.ProtoReflect.Descriptor instead.
func (*MoveIpAddressesResponse) Descriptor() ([]byte, []int) {
	return file_fleetmanager_grpc_fleetmanager_proto_rawDescGZIP(), []int{21}
}

// Hypervisor represents a hypervisor with its allocated resources and VMs.
type Hypervisor struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AllocatedMilliCpus   uint64                 `protobuf:"varint,1,opt,name=allocated_milli_cpus,json=allocatedMilliCpus,proto3" json:"allocated_milli_cpus,omitempty"`
	AllocatedMemory      uint64                 `protobuf:"varint,2,opt,name=allocated_memory,json=allocatedMemory,proto3" json:"allocated_memory,omitempty"` // MiB
	AllocatedVolumeBytes uint64                 `protobuf:"varint,3,opt,name=allocated_volume_bytes,json=allocatedVolumeBytes,proto3" json:"allocated_volume_bytes,omitempty"`
	Machine              *Machine               `protobuf:"bytes,4,opt,name=machine,proto3" json:"machine,omitempty"`
	Vms                  []*grpc1.VmInfo        `protobuf:"bytes,5,rep,name=vms,proto3" json:"vms,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Hypervisor) Reset() {
	*x = Hypervisor{}
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hypervisor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hypervisor) ProtoMessage() {}

func (x *Hypervisor) ProtoReflect() protoreflect.Message {
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hypervisor.ProtoReflect.Descriptor instead.
func (*Hypervisor) Descriptor() ([]byte, []int) {
	return file_fleetmanager_grpc_fleetmanager_proto_rawDescGZIP(), []int{22}
}

func (x *Hypervisor) GetAllocatedMilliCpus() uint64 {
	if x != nil {
		return x.AllocatedMilliCpus
	}
	return 0
}

func (x *Hypervisor) GetAllocatedMemory() uint64 {
	if x != nil {
		return x.AllocatedMemory
	}
	return 0
}

func (x *Hypervisor) GetAllocatedVolumeBytes() uint64 {
	if x != nil {
		return x.AllocatedVolumeBytes
	}
	return 0
}

func (x *Hypervisor) GetMachine() *Machine {
	if x != nil {
		return x.Machine
	}
	return nil
}

func (x *Hypervisor) GetVms() []*grpc1.VmInfo {
	if x != nil {
		return x.Vms
	}
	return nil
}

// Machine represents a physical or virtual machine in the fleet.
type Machine struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	GatewaySubnetId         string                 `protobuf:"bytes,1,opt,name=gateway_subnet_id,json=gatewaySubnetId,proto3" json:"gateway_subnet_id,omitempty"`
	Ipmi                    *NetworkEntry          `protobuf:"bytes,2,opt,name=ipmi,proto3" json:"ipmi,omitempty"`
	Location                string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	MemoryInMib             uint64                 `protobuf:"varint,4,opt,name=memory_in_mib,json=memoryInMib,proto3" json:"memory_in_mib,omitempty"`
	NetworkEntry            *NetworkEntry          `protobuf:"bytes,5,opt,name=network_entry,json=networkEntry,proto3" json:"network_entry,omitempty"`
	NumCpus                 uint32                 `protobuf:"varint,6,opt,name=num_cpus,json=numCpus,proto3" json:"num_cpus,omitempty"`
	OwnerGroups             []string               `protobuf:"bytes,7,rep,name=owner_groups,json=ownerGroups,proto3" json:"owner_groups,omitempty"`
	OwnerUsers              []string               `protobuf:"bytes,8,rep,name=owner_users,json=ownerUsers,proto3" json:"owner_users,omitempty"`
	SecondaryNetworkEntries []*NetworkEntry        `protobuf:"bytes,9,rep,name=secondary_network_entries,json=secondaryNetworkEntries,proto3" json:"secondary_network_entries,omitempty"`
	Tags                    *grpc.Tags             `protobuf:"bytes,10,opt,name=tags,proto3" json:"tags,omitempty"`
	TotalVolumeBytes        uint64                 `protobuf:"varint,11,opt,name=total_volume_bytes,json=totalVolumeBytes,proto3" json:"total_volume_bytes,omitempty"`
	Hostname                string                 `protobuf:"bytes,12,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Machine) Reset() {
	*x = Machine{}
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Machine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Machine) ProtoMessage() {}

func (x *Machine) ProtoReflect() protoreflect.Message {
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Machine.ProtoReflect.Descriptor instead.
func (*Machine) Descriptor() ([]byte, []int) {
	return file_fleetmanager_grpc_fleetmanager_proto_rawDescGZIP(), []int{23}
}

func (x *Machine) GetGatewaySubnetId() string {
	if x != nil {
		return x.GatewaySubnetId
	}
	return ""
}

func (x *Machine) GetIpmi() *NetworkEntry {
	if x != nil {
		return x.Ipmi
	}
	return nil
}

func (x *Machine) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Machine) GetMemoryInMib() uint64 {
	if x != nil {
		return x.MemoryInMib
	}
	return 0
}

func (x *Machine) GetNetworkEntry() *NetworkEntry {
	if x != nil {
		return x.NetworkEntry
	}
	return nil
}

func (x *Machine) GetNumCpus() uint32 {
	if x != nil {
		return x.NumCpus
	}
	return 0
}

func (x *Machine) GetOwnerGroups() []string {
	if x != nil {
		return x.OwnerGroups
	}
	return nil
}

func (x *Machine) GetOwnerUsers() []string {
	if x != nil {
		return x.OwnerUsers
	}
	return nil
}

func (x *Machine) GetSecondaryNetworkEntries() []*NetworkEntry {
	if x != nil {
		return x.SecondaryNetworkEntries
	}
	return nil
}

func (x *Machine) GetTags() *grpc.Tags {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Machine) GetTotalVolumeBytes() uint64 {
	if x != nil {
		return x.TotalVolumeBytes
	}
	return 0
}

func (x *Machine) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

// NetworkEntry represents a network interface configuration.
// Note: This is fleetmanager-specific. Hypervisor has its own NetworkEntry definition.
type NetworkEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Hostname       string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	HostIpAddress  []byte                 `protobuf:"bytes,2,opt,name=host_ip_address,json=hostIpAddress,proto3" json:"host_ip_address,omitempty"`
	HostMacAddress []byte                 `protobuf:"bytes,3,opt,name=host_mac_address,json=hostMacAddress,proto3" json:"host_mac_address,omitempty"`
	SubnetId       string                 `protobuf:"bytes,4,opt,name=subnet_id,json=subnetId,proto3" json:"subnet_id,omitempty"`
	VlanTrunk      bool                   `protobuf:"varint,5,opt,name=vlan_trunk,json=vlanTrunk,proto3" json:"vlan_trunk,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NetworkEntry) Reset() {
	*x = NetworkEntry{}
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkEntry) ProtoMessage() {}

func (x *NetworkEntry) ProtoReflect() protoreflect.Message {
	mi := &file_fleetmanager_grpc_fleetmanager_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkEntry.ProtoReflect.Descriptor instead.
func (*NetworkEntry) Descriptor() ([]byte, []int) {
	return file_fleetmanager_grpc_fleetmanager_proto_rawDescGZIP(), []int{24}
}

func (x *NetworkEntry) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NetworkEntry) GetHostIpAddress() []byte {
	if x != nil {
		return x.HostIpAddress
	}
	return nil
}

func (x *NetworkEntry) GetHostMacAddress() []byte {
	if x != nil {
		return x.HostMacAddress
	}
	return nil
}

func (x *NetworkEntry) GetSubnetId() string {
	if x != nil {
		return x.SubnetId
	}
	return ""
}

func (x *NetworkEntry) GetVlanTrunk() bool {
	if x != nil {
		return x.VlanTrunk
	}
	return false
}

var File_fleetmanager_grpc_fleetmanager_proto protoreflect.FileDescriptor

const file_fleetmanager_grpc_fleetmanager_proto_rawDesc = "" +
	"\n" +
	"$fleetmanager/grpc/fleetmanager.proto\x12\ffleetmanager\x1a\x1cgoogle/api/annotations.proto\x1a\x18common/grpc/common.proto\x1a hypervisor/grpc/hypervisor.proto\"X\n" +
	"\x18ChangeMachineTagsRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12 \n" +
	"\x04tags\x18\x02 \x01(\v2\f.common.TagsR\x04tags\"\x1b\n" +
	"\x19ChangeMachineTagsResponse\"n\n" +
	"\x15GetMachineInfoRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x129\n" +
	"\x19ignore_missing_local_tags\x18\x02 \x01(\bR\x16ignoreMissingLocalTags\"\x93\x01\n" +
	"\x16GetMachineInfoResponse\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x12/\n" +
	"\amachine\x18\x02 \x01(\v2\x15.fleetmanager.MachineR\amachine\x12,\n" +
	"\asubnets\x18\x03 \x03(\v2\x12.hypervisor.SubnetR\asubnets\":\n" +
	"\x19GetHypervisorForVMRequest\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\fR\tipAddress\"K\n" +
	"\x1aGetHypervisorForVMResponse\x12-\n" +
	"\x12hypervisor_address\x18\x01 \x01(\tR\x11hypervisorAddress\"C\n" +
	"\x1eListHypervisorLocationsRequest\x12!\n" +
	"\ftop_location\x18\x01 \x01(\tR\vtopLocation\"?\n" +
	"\x1fListHypervisorLocationsResponse\x12\x1c\n" +
	"\tlocations\x18\x01 \x03(\tR\tlocations\"\xfc\x01\n" +
	" ListHypervisorsInLocationRequest\x12J\n" +
	"\x18hypervisor_tags_to_match\x18\x01 \x01(\v2\x11.common.MatchTagsR\x15hypervisorTagsToMatch\x12+\n" +
	"\x11include_unhealthy\x18\x02 \x01(\bR\x10includeUnhealthy\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x1b\n" +
	"\tsubnet_id\x18\x04 \x01(\tR\bsubnetId\x12&\n" +
	"\x0ftags_to_include\x18\x05 \x03(\tR\rtagsToInclude\"\x96\x01\n" +
	"!ListHypervisorsInLocationResponse\x121\n" +
	"\x14hypervisor_addresses\x18\x01 \x03(\tR\x13hypervisorAddresses\x12>\n" +
	"\x14tags_for_hypervisors\x18\x02 \x03(\v2\f.common.TagsR\x12tagsForHypervisors\"j\n" +
	"\x11GetUpdatesRequest\x129\n" +
	"\x19ignore_missing_local_tags\x18\x01 \x01(\bR\x16ignoreMissingLocalTags\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\"\xc7\x03\n" +
	"\x06Update\x12@\n" +
	"\x10changed_machines\x18\x01 \x03(\v2\x15.fleetmanager.MachineR\x0fchangedMachines\x12E\n" +
	"\vchanged_vms\x18\x02 \x03(\v2$.fleetmanager.Update.ChangedVmsEntryR\n" +
	"changedVms\x12)\n" +
	"\x10deleted_machines\x18\x03 \x03(\tR\x0fdeletedMachines\x12\x1f\n" +
	"\vdeleted_vms\x18\x04 \x03(\tR\n" +
	"deletedVms\x12R\n" +
	"\x10vm_to_hypervisor\x18\x05 \x03(\v2(.fleetmanager.Update.VmToHypervisorEntryR\x0evmToHypervisor\x1aQ\n" +
	"\x0fChangedVmsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.hypervisor.VmInfoR\x05value:\x028\x01\x1aA\n" +
	"\x13VmToHypervisorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbe\x02\n" +
	"\x18ListVMsInLocationRequest\x12J\n" +
	"\x18hypervisor_tags_to_match\x18\x01 \x01(\v2\x11.common.MatchTagsR\x15hypervisorTagsToMatch\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12!\n" +
	"\fowner_groups\x18\x03 \x03(\tR\vownerGroups\x12\x1f\n" +
	"\vowner_users\x18\x04 \x03(\tR\n" +
	"ownerUsers\x12:\n" +
	"\x10vm_tags_to_match\x18\x05 \x01(\v2\x11.common.MatchTagsR\rvmTagsToMatch\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\a \x01(\tR\tpageToken\"f\n" +
	"\x19ListVMsInLocationResponse\x12!\n" +
	"\fip_addresses\x18\x01 \x03(\fR\vipAddresses\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"3\n" +
	"\x15PowerOnMachineRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"\x18\n" +
	"\x16PowerOnMachineResponse\"\xf4\x01\n" +
	"\x1fGetHypervisorsInLocationRequest\x12J\n" +
	"\x18hypervisor_tags_to_match\x18\x01 \x01(\v2\x11.common.MatchTagsR\x15hypervisorTagsToMatch\x12+\n" +
	"\x11include_unhealthy\x18\x02 \x01(\bR\x10includeUnhealthy\x12\x1f\n" +
	"\vinclude_vms\x18\x03 \x01(\bR\n" +
	"includeVms\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x1b\n" +
	"\tsubnet_id\x18\x05 \x01(\tR\bsubnetId\"^\n" +
	" GetHypervisorsInLocationResponse\x12:\n" +
	"\vhypervisors\x18\x01 \x03(\v2\x18.fleetmanager.HypervisorR\vhypervisors\"1\n" +
	"\x10GetIpInfoRequest\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\fR\tipAddress\"f\n" +
	"\x11GetIpInfoResponse\x12-\n" +
	"\x12hypervisor_address\x18\x01 \x01(\tR\x11hypervisorAddress\x12\"\n" +
	"\x02vm\x18\x02 \x01(\v2\x12.hypervisor.VmInfoR\x02vm\"l\n" +
	"\x16MoveIpAddressesRequest\x12/\n" +
	"\x13hypervisor_hostname\x18\x01 \x01(\tR\x12hypervisorHostname\x12!\n" +
	"\fip_addresses\x18\x02 \x03(\fR\vipAddresses\"\x19\n" +
	"\x17MoveIpAddressesResponse\"\xf6\x01\n" +
	"\n" +
	"Hypervisor\x120\n" +
	"\x14allocated_milli_cpus\x18\x01 \x01(\x04R\x12allocatedMilliCpus\x12)\n" +
	"\x10allocated_memory\x18\x02 \x01(\x04R\x0fallocatedMemory\x124\n" +
	"\x16allocated_volume_bytes\x18\x03 \x01(\x04R\x14allocatedVolumeBytes\x12/\n" +
	"\amachine\x18\x04 \x01(\v2\x15.fleetmanager.MachineR\amachine\x12$\n" +
	"\x03vms\x18\x05 \x03(\v2\x12.hypervisor.VmInfoR\x03vms\"\x89\x04\n" +
	"\aMachine\x12*\n" +
	"\x11gateway_subnet_id\x18\x01 \x01(\tR\x0fgatewaySubnetId\x12.\n" +
	"\x04ipmi\x18\x02 \x01(\v2\x1a.fleetmanager.NetworkEntryR\x04ipmi\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\"\n" +
	"\rmemory_in_mib\x18\x04 \x01(\x04R\vmemoryInMib\x12?\n" +
	"\rnetwork_entry\x18\x05 \x01(\v2\x1a.fleetmanager.NetworkEntryR\fnetworkEntry\x12\x19\n" +
	"\bnum_cpus\x18\x06 \x01(\rR\anumCpus\x12!\n" +
	"\fowner_groups\x18\a \x03(\tR\vownerGroups\x12\x1f\n" +
	"\vowner_users\x18\b \x03(\tR\n" +
	"ownerUsers\x12V\n" +
	"\x19secondary_network_entries\x18\t \x03(\v2\x1a.fleetmanager.NetworkEntryR\x17secondaryNetworkEntries\x12 \n" +
	"\x04tags\x18\n" +
	" \x01(\v2\f.common.TagsR\x04tags\x12,\n" +
	"\x12total_volume_bytes\x18\v \x01(\x04R\x10totalVolumeBytes\x12\x1a\n" +
	"\bhostname\x18\f \x01(\tR\bhostname\"\xb8\x01\n" +
	"\fNetworkEntry\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12&\n" +
	"\x0fhost_ip_address\x18\x02 \x01(\fR\rhostIpAddress\x12(\n" +
	"\x10host_mac_address\x18\x03 \x01(\fR\x0ehostMacAddress\x12\x1b\n" +
	"\tsubnet_id\x18\x04 \x01(\tR\bsubnetId\x12\x1d\n" +
	"\n" +
	"vlan_trunk\x18\x05 \x01(\bR\tvlanTrunk2\x83\f\n" +
	"\fFleetManager\x12|\n" +
	"\x0eGetMachineInfo\x12#.fleetmanager.GetMachineInfoRequest\x1a$.fleetmanager.GetMachineInfoResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/machines/{hostname}\x12\x83\x01\n" +
	"\x12GetHypervisorForVM\x12'.fleetmanager.GetHypervisorForVMRequest\x1a(.fleetmanager.GetHypervisorForVMResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/vms/hypervisor\x12\x8d\x01\n" +
	"\x17ListHypervisorLocations\x12,.fleetmanager.ListHypervisorLocationsRequest\x1a-.fleetmanager.ListHypervisorLocationsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/locations\x12\xaa\x01\n" +
	"\x19ListHypervisorsInLocation\x12..fleetmanager.ListHypervisorsInLocationRequest\x1a/.fleetmanager.ListHypervisorsInLocationResponse\",\x82\xd3\xe4\x93\x02&\x12$/v1/locations/{location}/hypervisors\x12\x85\x01\n" +
	"\x0ePowerOnMachine\x12#.fleetmanager.PowerOnMachineRequest\x1a$.fleetmanager.PowerOnMachineResponse\"(\x82\xd3\xe4\x93\x02\"\" /v1/machines/{hostname}/power-on\x12\x8d\x01\n" +
	"\x11ChangeMachineTags\x12&.fleetmanager.ChangeMachineTagsRequest\x1a'.fleetmanager.ChangeMachineTagsResponse\"'\x82\xd3\xe4\x93\x02!:\x01*2\x1c/v1/machines/{hostname}/tags\x12\xb0\x01\n" +
	"\x18GetHypervisorsInLocation\x12-.fleetmanager.GetHypervisorsInLocationRequest\x1a..fleetmanager.GetHypervisorsInLocationResponse\"5\x82\xd3\xe4\x93\x02/:\x01*\"*/v1/locations/{location}/hypervisors/query\x12b\n" +
	"\tGetIpInfo\x12\x1e.fleetmanager.GetIpInfoRequest\x1a\x1f.fleetmanager.GetIpInfoResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/ips/info\x12\x99\x01\n" +
	"\x0fMoveIpAddresses\x12$.fleetmanager.MoveIpAddressesRequest\x1a%.fleetmanager.MoveIpAddressesResponse\"9\x82\xd3\xe4\x93\x023:\x01*\"./v1/hypervisors/{hypervisor_hostname}/move-ips\x12\x8a\x01\n" +
	"\x11ListVMsInLocation\x12&.fleetmanager.ListVMsInLocationRequest\x1a'.fleetmanager.ListVMsInLocationResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/locations/{location}/vms\x12Z\n" +
	"\n" +
	"GetUpdates\x12\x1f.fleetmanager.GetUpdatesRequest\x1a\x14.fleetmanager.Update\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/updates0\x01B@Z>github.com/Cloud-Foundations/Dominator/proto/fleetmanager/grpcb\x06proto3"

var (
	file_fleetmanager_grpc_fleetmanager_proto_rawDescOnce sync.Once
	file_fleetmanager_grpc_fleetmanager_proto_rawDescData []byte
)

func file_fleetmanager_grpc_fleetmanager_proto_rawDescGZIP() []byte {
	file_fleetmanager_grpc_fleetmanager_proto_rawDescOnce.Do(func() {
		file_fleetmanager_grpc_fleetmanager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleetmanager_grpc_fleetmanager_proto_rawDesc), len(file_fleetmanager_grpc_fleetmanager_proto_rawDesc)))
	})
	return file_fleetmanager_grpc_fleetmanager_proto_rawDescData
}

var file_fleetmanager_grpc_fleetmanager_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_fleetmanager_grpc_fleetmanager_proto_goTypes = []any{
	(*ChangeMachineTagsRequest)(nil),          // 0: fleetmanager.ChangeMachineTagsRequest
	(*ChangeMachineTagsResponse)(nil),         // 1: fleetmanager.ChangeMachineTagsResponse
	(*GetMachineInfoRequest)(nil),             // 2: fleetmanager.GetMachineInfoRequest
	(*GetMachineInfoResponse)(nil),            // 3: fleetmanager.GetMachineInfoResponse
	(*GetHypervisorForVMRequest)(nil),         // 4: fleetmanager.GetHypervisorForVMRequest
	(*GetHypervisorForVMResponse)(nil),        // 5: fleetmanager.GetHypervisorForVMResponse
	(*ListHypervisorLocationsRequest)(nil),    // 6: fleetmanager.ListHypervisorLocationsRequest
	(*ListHypervisorLocationsResponse)(nil),   // 7: fleetmanager.ListHypervisorLocationsResponse
	(*ListHypervisorsInLocationRequest)(nil),  // 8: fleetmanager.ListHypervisorsInLocationRequest
	(*ListHypervisorsInLocationResponse)(nil), // 9: fleetmanager.ListHypervisorsInLocationResponse
	(*GetUpdatesRequest)(nil),                 // 10: fleetmanager.GetUpdatesRequest
	(*Update)(nil),                            // 11: fleetmanager.Update
	(*ListVMsInLocationRequest)(nil),          // 12: fleetmanager.ListVMsInLocationRequest
	(*ListVMsInLocationResponse)(nil),         // 13: fleetmanager.ListVMsInLocationResponse
	(*PowerOnMachineRequest)(nil),             // 14: fleetmanager.PowerOnMachineRequest
	(*PowerOnMachineResponse)(nil),            // 15: fleetmanager.PowerOnMachineResponse
	(*GetHypervisorsInLocationRequest)(nil),   // 16: fleetmanager.GetHypervisorsInLocationRequest
	(*GetHypervisorsInLocationResponse)(nil),  // 17: fleetmanager.GetHypervisorsInLocationResponse
	(*GetIpInfoRequest)(nil),                  // 18: fleetmanager.GetIpInfoRequest
	(*GetIpInfoResponse)(nil),                 // 19: fleetmanager.GetIpInfoResponse
	(*MoveIpAddressesRequest)(nil),            // 20: fleetmanager.MoveIpAddressesRequest
	(*MoveIpAddressesResponse)(nil),           // 21: fleetmanager.MoveIpAddressesResponse
	(*Hypervisor)(nil),                        // 22: fleetmanager.Hypervisor
	(*Machine)(nil),                           // 23: fleetmanager.Machine
	(*NetworkEntry)(nil),                      // 24: fleetmanager.NetworkEntry
	nil,                                       // 25: fleetmanager.Update.ChangedVmsEntry
	nil,                                       // 26: fleetmanager.Update.VmToHypervisorEntry
	(*grpc.Tags)(nil),                         // 27: common.Tags
	(*grpc1.Subnet)(nil),                      // 28: hypervisor.Subnet
	(*grpc.MatchTags)(nil),                    // 29: common.MatchTags
	(*grpc1.VmInfo)(nil),                      // 30: hypervisor.VmInfo
}
var file_fleetmanager_grpc_fleetmanager_proto_depIdxs = []int32{
	27, // 0: fleetmanager.ChangeMachineTagsRequest.tags:type_name -> common.Tags
	23, // 1: fleetmanager.GetMachineInfoResponse.machine:type_name -> fleetmanager.Machine
	28, // 2: fleetmanager.GetMachineInfoResponse.subnets:type_name -> hypervisor.Subnet
	29, // 3: fleetmanager.ListHypervisorsInLocationRequest.hypervisor_tags_to_match:type_name -> common.MatchTags
	27, // 4: fleetmanager.ListHypervisorsInLocationResponse.tags_for_hypervisors:type_name -> common.Tags
	23, // 5: fleetmanager.Update.changed_machines:type_name -> fleetmanager.Machine
	25, // 6: fleetmanager.Update.changed_vms:type_name -> fleetmanager.Update.ChangedVmsEntry
	26, // 7: fleetmanager.Update.vm_to_hypervisor:type_name -> fleetmanager.Update.VmToHypervisorEntry
	29, // 8: fleetmanager.ListVMsInLocationRequest.hypervisor_tags_to_match:type_name -> common.MatchTags
	29, // 9: fleetmanager.ListVMsInLocationRequest.vm_tags_to_match:type_name -> common.MatchTags
	29, // 10: fleetmanager.GetHypervisorsInLocationRequest.hypervisor_tags_to_match:type_name -> common.MatchTags
	22, // 11: fleetmanager.GetHypervisorsInLocationResponse.hypervisors:type_name -> fleetmanager.Hypervisor
	30, // 12: fleetmanager.GetIpInfoResponse.vm:type_name -> hypervisor.VmInfo
	23, // 13: fleetmanager.Hypervisor.machine:type_name -> fleetmanager.Machine
	30, // 14: fleetmanager.Hypervisor.vms:type_name -> hypervisor.VmInfo
	24, // 15: fleetmanager.Machine.ipmi:type_name -> fleetmanager.NetworkEntry
	24, // 16: fleetmanager.Machine.network_entry:type_name -> fleetmanager.NetworkEntry
	24, // 17: fleetmanager.Machine.secondary_network_entries:type_name -> fleetmanager.NetworkEntry
	27, // 18: fleetmanager.Machine.tags:type_name -> common.Tags
	30, // 19: fleetmanager.Update.ChangedVmsEntry.value:type_name -> hypervisor.VmInfo
	2,  // 20: fleetmanager.FleetManager.GetMachineInfo:input_type -> fleetmanager.GetMachineInfoRequest
	4,  // 21: fleetmanager.FleetManager.GetHypervisorForVM:input_type -> fleetmanager.GetHypervisorForVMRequest
	6,  // 22: fleetmanager.FleetManager.ListHypervisorLocations:input_type -> fleetmanager.ListHypervisorLocationsRequest
	8,  // 23: fleetmanager.FleetManager.ListHypervisorsInLocation:input_type -> fleetmanager.ListHypervisorsInLocationRequest
	14, // 24: fleetmanager.FleetManager.PowerOnMachine:input_type -> fleetmanager.PowerOnMachineRequest
	0,  // 25: fleetmanager.FleetManager.ChangeMachineTags:input_type -> fleetmanager.ChangeMachineTagsRequest
	16, // 26: fleetmanager.FleetManager.GetHypervisorsInLocation:input_type -> fleetmanager.GetHypervisorsInLocationRequest
	18, // 27: fleetmanager.FleetManager.GetIpInfo:input_type -> fleetmanager.GetIpInfoRequest
	20, // 28: fleetmanager.FleetManager.MoveIpAddresses:input_type -> fleetmanager.MoveIpAddressesRequest
	12, // 29: fleetmanager.FleetManager.ListVMsInLocation:input_type -> fleetmanager.ListVMsInLocationRequest
	10, // 30: fleetmanager.FleetManager.GetUpdates:input_type -> fleetmanager.GetUpdatesRequest
	3,  // 31: fleetmanager.FleetManager.GetMachineInfo:output_type -> fleetmanager.GetMachineInfoResponse
	5,  // 32: fleetmanager.FleetManager.GetHypervisorForVM:output_type -> fleetmanager.GetHypervisorForVMResponse
	7,  // 33: fleetmanager.FleetManager.ListHypervisorLocations:output_type -> fleetmanager.ListHypervisorLocationsResponse
	9,  // 34: fleetmanager.FleetManager.ListHypervisorsInLocation:output_type -> fleetmanager.ListHypervisorsInLocationResponse
	15, // 35: fleetmanager.FleetManager.PowerOnMachine:output_type -> fleetmanager.PowerOnMachineResponse
	1,  // 36: fleetmanager.FleetManager.ChangeMachineTags:output_type -> fleetmanager.ChangeMachineTagsResponse
	17, // 37: fleetmanager.FleetManager.GetHypervisorsInLocation:output_type -> fleetmanager.GetHypervisorsInLocationResponse
	19, // 38: fleetmanager.FleetManager.GetIpInfo:output_type -> fleetmanager.GetIpInfoResponse
	21, // 39: fleetmanager.FleetManager.MoveIpAddresses:output_type -> fleetmanager.MoveIpAddressesResponse
	13, // 40: fleetmanager.FleetManager.ListVMsInLocation:output_type -> fleetmanager.ListVMsInLocationResponse
	11, // 41: fleetmanager.FleetManager.GetUpdates:output_type -> fleetmanager.Update
	31, // [31:42] is the sub-list for method output_type
	20, // [20:31] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_fleetmanager_grpc_fleetmanager_proto_init() }
func file_fleetmanager_grpc_fleetmanager_proto_init() {
	if File_fleetmanager_grpc_fleetmanager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleetmanager_grpc_fleetmanager_proto_rawDesc), len(file_fleetmanager_grpc_fleetmanager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fleetmanager_grpc_fleetmanager_proto_goTypes,
		DependencyIndexes: file_fleetmanager_grpc_fleetmanager_proto_depIdxs,
		MessageInfos:      file_fleetmanager_grpc_fleetmanager_proto_msgTypes,
	}.Build()
	File_fleetmanager_grpc_fleetmanager_proto = out.File
	file_fleetmanager_grpc_fleetmanager_proto_goTypes = nil
	file_fleetmanager_grpc_fleetmanager_proto_depIdxs = nil
}
