// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: fleetmanager/grpc/fleetmanager.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FleetManager_GetMachineInfo_FullMethodName            = "/fleetmanager.FleetManager/GetMachineInfo"
	FleetManager_GetHypervisorForVM_FullMethodName        = "/fleetmanager.FleetManager/GetHypervisorForVM"
	FleetManager_ListHypervisorLocations_FullMethodName   = "/fleetmanager.FleetManager/ListHypervisorLocations"
	FleetManager_ListHypervisorsInLocation_FullMethodName = "/fleetmanager.FleetManager/ListHypervisorsInLocation"
	FleetManager_PowerOnMachine_FullMethodName            = "/fleetmanager.FleetManager/PowerOnMachine"
	FleetManager_ChangeMachineTags_FullMethodName         = "/fleetmanager.FleetManager/ChangeMachineTags"
	FleetManager_GetHypervisorsInLocation_FullMethodName  = "/fleetmanager.FleetManager/GetHypervisorsInLocation"
	FleetManager_GetIpInfo_FullMethodName                 = "/fleetmanager.FleetManager/GetIpInfo"
	FleetManager_MoveIpAddresses_FullMethodName           = "/fleetmanager.FleetManager/MoveIpAddresses"
	FleetManager_ListVMsInLocation_FullMethodName         = "/fleetmanager.FleetManager/ListVMsInLocation"
	FleetManager_GetUpdates_FullMethodName                = "/fleetmanager.FleetManager/GetUpdates"
)

// FleetManagerClient is the client API for FleetManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FleetManager service - embedded gRPC interface for fleet-manager daemon
type FleetManagerClient interface {
	// Unary RPCs
	GetMachineInfo(ctx context.Context, in *GetMachineInfoRequest, opts ...grpc.CallOption) (*GetMachineInfoResponse, error)
	GetHypervisorForVM(ctx context.Context, in *GetHypervisorForVMRequest, opts ...grpc.CallOption) (*GetHypervisorForVMResponse, error)
	ListHypervisorLocations(ctx context.Context, in *ListHypervisorLocationsRequest, opts ...grpc.CallOption) (*ListHypervisorLocationsResponse, error)
	ListHypervisorsInLocation(ctx context.Context, in *ListHypervisorsInLocationRequest, opts ...grpc.CallOption) (*ListHypervisorsInLocationResponse, error)
	PowerOnMachine(ctx context.Context, in *PowerOnMachineRequest, opts ...grpc.CallOption) (*PowerOnMachineResponse, error)
	ChangeMachineTags(ctx context.Context, in *ChangeMachineTagsRequest, opts ...grpc.CallOption) (*ChangeMachineTagsResponse, error)
	GetHypervisorsInLocation(ctx context.Context, in *GetHypervisorsInLocationRequest, opts ...grpc.CallOption) (*GetHypervisorsInLocationResponse, error)
	GetIpInfo(ctx context.Context, in *GetIpInfoRequest, opts ...grpc.CallOption) (*GetIpInfoResponse, error)
	MoveIpAddresses(ctx context.Context, in *MoveIpAddressesRequest, opts ...grpc.CallOption) (*MoveIpAddressesResponse, error)
	ListVMsInLocation(ctx context.Context, in *ListVMsInLocationRequest, opts ...grpc.CallOption) (*ListVMsInLocationResponse, error)
	// Server streaming RPCs
	GetUpdates(ctx context.Context, in *GetUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Update], error)
}

type fleetManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewFleetManagerClient(cc grpc.ClientConnInterface) FleetManagerClient {
	return &fleetManagerClient{cc}
}

func (c *fleetManagerClient) GetMachineInfo(ctx context.Context, in *GetMachineInfoRequest, opts ...grpc.CallOption) (*GetMachineInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMachineInfoResponse)
	err := c.cc.Invoke(ctx, FleetManager_GetMachineInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetManagerClient) GetHypervisorForVM(ctx context.Context, in *GetHypervisorForVMRequest, opts ...grpc.CallOption) (*GetHypervisorForVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHypervisorForVMResponse)
	err := c.cc.Invoke(ctx, FleetManager_GetHypervisorForVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetManagerClient) ListHypervisorLocations(ctx context.Context, in *ListHypervisorLocationsRequest, opts ...grpc.CallOption) (*ListHypervisorLocationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHypervisorLocationsResponse)
	err := c.cc.Invoke(ctx, FleetManager_ListHypervisorLocations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetManagerClient) ListHypervisorsInLocation(ctx context.Context, in *ListHypervisorsInLocationRequest, opts ...grpc.CallOption) (*ListHypervisorsInLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHypervisorsInLocationResponse)
	err := c.cc.Invoke(ctx, FleetManager_ListHypervisorsInLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetManagerClient) PowerOnMachine(ctx context.Context, in *PowerOnMachineRequest, opts ...grpc.CallOption) (*PowerOnMachineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PowerOnMachineResponse)
	err := c.cc.Invoke(ctx, FleetManager_PowerOnMachine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetManagerClient) ChangeMachineTags(ctx context.Context, in *ChangeMachineTagsRequest, opts ...grpc.CallOption) (*ChangeMachineTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeMachineTagsResponse)
	err := c.cc.Invoke(ctx, FleetManager_ChangeMachineTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetManagerClient) GetHypervisorsInLocation(ctx context.Context, in *GetHypervisorsInLocationRequest, opts ...grpc.CallOption) (*GetHypervisorsInLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHypervisorsInLocationResponse)
	err := c.cc.Invoke(ctx, FleetManager_GetHypervisorsInLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetManagerClient) GetIpInfo(ctx context.Context, in *GetIpInfoRequest, opts ...grpc.CallOption) (*GetIpInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIpInfoResponse)
	err := c.cc.Invoke(ctx, FleetManager_GetIpInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetManagerClient) MoveIpAddresses(ctx context.Context, in *MoveIpAddressesRequest, opts ...grpc.CallOption) (*MoveIpAddressesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoveIpAddressesResponse)
	err := c.cc.Invoke(ctx, FleetManager_MoveIpAddresses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetManagerClient) ListVMsInLocation(ctx context.Context, in *ListVMsInLocationRequest, opts ...grpc.CallOption) (*ListVMsInLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVMsInLocationResponse)
	err := c.cc.Invoke(ctx, FleetManager_ListVMsInLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetManagerClient) GetUpdates(ctx context.Context, in *GetUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Update], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FleetManager_ServiceDesc.Streams[0], FleetManager_GetUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetUpdatesRequest, Update]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetManager_GetUpdatesClient = grpc.ServerStreamingClient[Update]

// FleetManagerServer is the server API for FleetManager service.
// All implementations should embed UnimplementedFleetManagerServer
// for forward compatibility.
//
// FleetManager service - embedded gRPC interface for fleet-manager daemon
type FleetManagerServer interface {
	// Unary RPCs
	GetMachineInfo(context.Context, *GetMachineInfoRequest) (*GetMachineInfoResponse, error)
	GetHypervisorForVM(context.Context, *GetHypervisorForVMRequest) (*GetHypervisorForVMResponse, error)
	ListHypervisorLocations(context.Context, *ListHypervisorLocationsRequest) (*ListHypervisorLocationsResponse, error)
	ListHypervisorsInLocation(context.Context, *ListHypervisorsInLocationRequest) (*ListHypervisorsInLocationResponse, error)
	PowerOnMachine(context.Context, *PowerOnMachineRequest) (*PowerOnMachineResponse, error)
	ChangeMachineTags(context.Context, *ChangeMachineTagsRequest) (*ChangeMachineTagsResponse, error)
	GetHypervisorsInLocation(context.Context, *GetHypervisorsInLocationRequest) (*GetHypervisorsInLocationResponse, error)
	GetIpInfo(context.Context, *GetIpInfoRequest) (*GetIpInfoResponse, error)
	MoveIpAddresses(context.Context, *MoveIpAddressesRequest) (*MoveIpAddressesResponse, error)
	ListVMsInLocation(context.Context, *ListVMsInLocationRequest) (*ListVMsInLocationResponse, error)
	// Server streaming RPCs
	GetUpdates(*GetUpdatesRequest, grpc.ServerStreamingServer[Update]) error
}

// UnimplementedFleetManagerServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFleetManagerServer struct{}

func (UnimplementedFleetManagerServer) GetMachineInfo(context.Context, *GetMachineInfoRequest) (*GetMachineInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMachineInfo not implemented")
}
func (UnimplementedFleetManagerServer) GetHypervisorForVM(context.Context, *GetHypervisorForVMRequest) (*GetHypervisorForVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHypervisorForVM not implemented")
}
func (UnimplementedFleetManagerServer) ListHypervisorLocations(context.Context, *ListHypervisorLocationsRequest) (*ListHypervisorLocationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHypervisorLocations not implemented")
}
func (UnimplementedFleetManagerServer) ListHypervisorsInLocation(context.Context, *ListHypervisorsInLocationRequest) (*ListHypervisorsInLocationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHypervisorsInLocation not implemented")
}
func (UnimplementedFleetManagerServer) PowerOnMachine(context.Context, *PowerOnMachineRequest) (*PowerOnMachineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PowerOnMachine not implemented")
}
func (UnimplementedFleetManagerServer) ChangeMachineTags(context.Context, *ChangeMachineTagsRequest) (*ChangeMachineTagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeMachineTags not implemented")
}
func (UnimplementedFleetManagerServer) GetHypervisorsInLocation(context.Context, *GetHypervisorsInLocationRequest) (*GetHypervisorsInLocationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHypervisorsInLocation not implemented")
}
func (UnimplementedFleetManagerServer) GetIpInfo(context.Context, *GetIpInfoRequest) (*GetIpInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIpInfo not implemented")
}
func (UnimplementedFleetManagerServer) MoveIpAddresses(context.Context, *MoveIpAddressesRequest) (*MoveIpAddressesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveIpAddresses not implemented")
}
func (UnimplementedFleetManagerServer) ListVMsInLocation(context.Context, *ListVMsInLocationRequest) (*ListVMsInLocationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVMsInLocation not implemented")
}
func (UnimplementedFleetManagerServer) GetUpdates(*GetUpdatesRequest, grpc.ServerStreamingServer[Update]) error {
	return status.Error(codes.Unimplemented, "method GetUpdates not implemented")
}
func (UnimplementedFleetManagerServer) testEmbeddedByValue() {}

// UnsafeFleetManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FleetManagerServer will
// result in compilation errors.
type UnsafeFleetManagerServer interface {
	mustEmbedUnimplementedFleetManagerServer()
}

func RegisterFleetManagerServer(s grpc.ServiceRegistrar, srv FleetManagerServer) {
	// If the following call panics, it indicates UnimplementedFleetManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FleetManager_ServiceDesc, srv)
}

func _FleetManager_GetMachineInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMachineInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetManagerServer).GetMachineInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetManager_GetMachineInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetManagerServer).GetMachineInfo(ctx, req.(*GetMachineInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetManager_GetHypervisorForVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHypervisorForVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetManagerServer).GetHypervisorForVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetManager_GetHypervisorForVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetManagerServer).GetHypervisorForVM(ctx, req.(*GetHypervisorForVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetManager_ListHypervisorLocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHypervisorLocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetManagerServer).ListHypervisorLocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetManager_ListHypervisorLocations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetManagerServer).ListHypervisorLocations(ctx, req.(*ListHypervisorLocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetManager_ListHypervisorsInLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHypervisorsInLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetManagerServer).ListHypervisorsInLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetManager_ListHypervisorsInLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetManagerServer).ListHypervisorsInLocation(ctx, req.(*ListHypervisorsInLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetManager_PowerOnMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PowerOnMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetManagerServer).PowerOnMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetManager_PowerOnMachine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetManagerServer).PowerOnMachine(ctx, req.(*PowerOnMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetManager_ChangeMachineTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeMachineTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetManagerServer).ChangeMachineTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetManager_ChangeMachineTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetManagerServer).ChangeMachineTags(ctx, req.(*ChangeMachineTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetManager_GetHypervisorsInLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHypervisorsInLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetManagerServer).GetHypervisorsInLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetManager_GetHypervisorsInLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetManagerServer).GetHypervisorsInLocation(ctx, req.(*GetHypervisorsInLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetManager_GetIpInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIpInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetManagerServer).GetIpInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetManager_GetIpInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetManagerServer).GetIpInfo(ctx, req.(*GetIpInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetManager_MoveIpAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveIpAddressesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetManagerServer).MoveIpAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetManager_MoveIpAddresses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetManagerServer).MoveIpAddresses(ctx, req.(*MoveIpAddressesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetManager_ListVMsInLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVMsInLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetManagerServer).ListVMsInLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetManager_ListVMsInLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetManagerServer).ListVMsInLocation(ctx, req.(*ListVMsInLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetManager_GetUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetUpdatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FleetManagerServer).GetUpdates(m, &grpc.GenericServerStream[GetUpdatesRequest, Update]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetManager_GetUpdatesServer = grpc.ServerStreamingServer[Update]

// FleetManager_ServiceDesc is the grpc.ServiceDesc for FleetManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FleetManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleetmanager.FleetManager",
	HandlerType: (*FleetManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMachineInfo",
			Handler:    _FleetManager_GetMachineInfo_Handler,
		},
		{
			MethodName: "GetHypervisorForVM",
			Handler:    _FleetManager_GetHypervisorForVM_Handler,
		},
		{
			MethodName: "ListHypervisorLocations",
			Handler:    _FleetManager_ListHypervisorLocations_Handler,
		},
		{
			MethodName: "ListHypervisorsInLocation",
			Handler:    _FleetManager_ListHypervisorsInLocation_Handler,
		},
		{
			MethodName: "PowerOnMachine",
			Handler:    _FleetManager_PowerOnMachine_Handler,
		},
		{
			MethodName: "ChangeMachineTags",
			Handler:    _FleetManager_ChangeMachineTags_Handler,
		},
		{
			MethodName: "GetHypervisorsInLocation",
			Handler:    _FleetManager_GetHypervisorsInLocation_Handler,
		},
		{
			MethodName: "GetIpInfo",
			Handler:    _FleetManager_GetIpInfo_Handler,
		},
		{
			MethodName: "MoveIpAddresses",
			Handler:    _FleetManager_MoveIpAddresses_Handler,
		},
		{
			MethodName: "ListVMsInLocation",
			Handler:    _FleetManager_ListVMsInLocation_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetUpdates",
			Handler:       _FleetManager_GetUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "fleetmanager/grpc/fleetmanager.proto",
}
