package hypervisor

// Code generated by proto-gen. DO NOT EDIT.

import (
	"net"
	"time"

	"github.com/Cloud-Foundations/Dominator/lib/tags"
	pb "github.com/Cloud-Foundations/Dominator/proto/hypervisor/grpc"
)

// AcknowledgeVmResponseToProto converts SRPC AcknowledgeVmResponse to protobuf AcknowledgeVmResponse
func AcknowledgeVmResponseToProto(src *AcknowledgeVmResponse) *pb.AcknowledgeVmResponse {
	if src == nil {
		return nil
	}
	return &pb.AcknowledgeVmResponse{
	}
}

// AcknowledgeVmResponseFromProto converts protobuf AcknowledgeVmResponse to SRPC AcknowledgeVmResponse
func AcknowledgeVmResponseFromProto(src *pb.AcknowledgeVmResponse) *AcknowledgeVmResponse {
	if src == nil {
		return nil
	}
	return &AcknowledgeVmResponse{
	}
}

// GetVmInfoRequestToProto converts SRPC GetVmInfoRequest to protobuf GetVmInfoRequest
func GetVmInfoRequestToProto(src *GetVmInfoRequest) *pb.GetVmInfoRequest {
	if src == nil {
		return nil
	}
	return &pb.GetVmInfoRequest{
		IpAddress: []byte(src.IpAddress),
	}
}

// GetVmInfoRequestFromProto converts protobuf GetVmInfoRequest to SRPC GetVmInfoRequest
func GetVmInfoRequestFromProto(src *pb.GetVmInfoRequest) *GetVmInfoRequest {
	if src == nil {
		return nil
	}
	return &GetVmInfoRequest{
		IpAddress: net.IP(src.IpAddress),
	}
}

// GetVmInfoResponseToProto converts SRPC GetVmInfoResponse to protobuf GetVmInfoResponse
func GetVmInfoResponseToProto(src *GetVmInfoResponse) *pb.GetVmInfoResponse {
	if src == nil {
		return nil
	}
	return &pb.GetVmInfoResponse{
		VmInfo: VmInfoToProto(&src.VmInfo),
	}
}

// GetVmInfoResponseFromProto converts protobuf GetVmInfoResponse to SRPC GetVmInfoResponse
func GetVmInfoResponseFromProto(src *pb.GetVmInfoResponse) *GetVmInfoResponse {
	if src == nil {
		return nil
	}
	return &GetVmInfoResponse{
		VmInfo: *VmInfoFromProto(src.VmInfo),
	}
}

// AcknowledgeVmRequestToProto converts SRPC AcknowledgeVmRequest to protobuf AcknowledgeVmRequest
func AcknowledgeVmRequestToProto(src *AcknowledgeVmRequest) *pb.AcknowledgeVmRequest {
	if src == nil {
		return nil
	}
	return &pb.AcknowledgeVmRequest{
		IpAddress: []byte(src.IpAddress),
	}
}

// AcknowledgeVmRequestFromProto converts protobuf AcknowledgeVmRequest to SRPC AcknowledgeVmRequest
func AcknowledgeVmRequestFromProto(src *pb.AcknowledgeVmRequest) *AcknowledgeVmRequest {
	if src == nil {
		return nil
	}
	return &AcknowledgeVmRequest{
		IpAddress: net.IP(src.IpAddress),
	}
}

// VmInfoToProto converts SRPC VmInfo to protobuf VmInfo
func VmInfoToProto(src *VmInfo) *pb.VmInfo {
	if src == nil {
		return nil
	}
	return &pb.VmInfo{
		Address: AddressToProto(&src.Address),
		ChangedStateOn: src.ChangedStateOn.Unix(),
		ConsoleType: uint32(src.ConsoleType),
		CreatedOn: src.CreatedOn.Unix(),
		CpuPriority: int32(src.CpuPriority),
		DestroyOnPowerdown: src.DestroyOnPowerdown,
		DestroyProtection: src.DestroyProtection,
		DisableVirtIO: src.DisableVirtIO,
		ExtraKernelOptions: src.ExtraKernelOptions,
		FirmwareType: uint32(src.FirmwareType),
		Hostname: src.Hostname,
		IdentityExpires: src.IdentityExpires.Unix(),
		IdentityName: src.IdentityName,
		ImageName: src.ImageName,
		ImageURL: src.ImageURL,
		MachineType: uint32(src.MachineType),
		MemoryInMiB: src.MemoryInMiB,
		MilliCPUs: uint32(src.MilliCPUs),
		NetworkEntries: convertNetworkEntrySliceToProto(src.NetworkEntries),
		OwnerGroups: src.OwnerGroups,
		OwnerUsers: src.OwnerUsers,
		RootFileSystemLabel: src.RootFileSystemLabel,
		SpreadVolumes: src.SpreadVolumes,
		State: uint32(src.State),
		SecondaryAddresses: convertAddressSliceToProto(src.SecondaryAddresses),
		SecondarySubnetIDs: src.SecondarySubnetIDs,
		SubnetId: src.SubnetId,
		Tags: map[string]string(src.Tags),
		Uncommitted: src.Uncommitted,
		VirtualCPUs: uint32(src.VirtualCPUs),
		Volumes: convertVolumeSliceToProto(src.Volumes),
		WatchdogAction: uint32(src.WatchdogAction),
		WatchdogModel: uint32(src.WatchdogModel),
	}
}

// VmInfoFromProto converts protobuf VmInfo to SRPC VmInfo
func VmInfoFromProto(src *pb.VmInfo) *VmInfo {
	if src == nil {
		return nil
	}
	return &VmInfo{
		Address: *AddressFromProto(src.Address),
		ChangedStateOn: time.Unix(src.ChangedStateOn, 0),
		ConsoleType: ConsoleType(src.ConsoleType),
		CreatedOn: time.Unix(src.CreatedOn, 0),
		CpuPriority: int(src.CpuPriority),
		DestroyOnPowerdown: src.DestroyOnPowerdown,
		DestroyProtection: src.DestroyProtection,
		DisableVirtIO: src.DisableVirtIO,
		ExtraKernelOptions: src.ExtraKernelOptions,
		FirmwareType: FirmwareType(src.FirmwareType),
		Hostname: src.Hostname,
		IdentityExpires: time.Unix(src.IdentityExpires, 0),
		IdentityName: src.IdentityName,
		ImageName: src.ImageName,
		ImageURL: src.ImageURL,
		MachineType: MachineType(src.MachineType),
		MemoryInMiB: src.MemoryInMiB,
		MilliCPUs: uint(src.MilliCPUs),
		NetworkEntries: convertNetworkEntrySliceFromProto(src.NetworkEntries),
		OwnerGroups: src.OwnerGroups,
		OwnerUsers: src.OwnerUsers,
		RootFileSystemLabel: src.RootFileSystemLabel,
		SpreadVolumes: src.SpreadVolumes,
		State: State(src.State),
		SecondaryAddresses: convertAddressSliceFromProto(src.SecondaryAddresses),
		SecondarySubnetIDs: src.SecondarySubnetIDs,
		SubnetId: src.SubnetId,
		Tags: tags.Tags(src.Tags),
		Uncommitted: src.Uncommitted,
		VirtualCPUs: uint(src.VirtualCPUs),
		Volumes: convertVolumeSliceFromProto(src.Volumes),
		WatchdogAction: WatchdogAction(src.WatchdogAction),
		WatchdogModel: WatchdogModel(src.WatchdogModel),
	}
}

// AddressToProto converts SRPC Address to protobuf Address
func AddressToProto(src *Address) *pb.Address {
	if src == nil {
		return nil
	}
	return &pb.Address{
		IpAddress: []byte(src.IpAddress),
		MacAddress: src.MacAddress,
	}
}

// AddressFromProto converts protobuf Address to SRPC Address
func AddressFromProto(src *pb.Address) *Address {
	if src == nil {
		return nil
	}
	return &Address{
		IpAddress: net.IP(src.IpAddress),
		MacAddress: src.MacAddress,
	}
}

// NetworkEntryToProto converts SRPC NetworkEntry to protobuf NetworkEntry
func NetworkEntryToProto(src *NetworkEntry) *pb.NetworkEntry {
	if src == nil {
		return nil
	}
	return &pb.NetworkEntry{
		NumQueues: uint32(src.NumQueues),
	}
}

// NetworkEntryFromProto converts protobuf NetworkEntry to SRPC NetworkEntry
func NetworkEntryFromProto(src *pb.NetworkEntry) *NetworkEntry {
	if src == nil {
		return nil
	}
	return &NetworkEntry{
		NumQueues: uint(src.NumQueues),
	}
}

// VolumeToProto converts SRPC Volume to protobuf Volume
func VolumeToProto(src *Volume) *pb.Volume {
	if src == nil {
		return nil
	}
	return &pb.Volume{
		Format: uint32(src.Format),
		Interface: uint32(src.Interface),
		Size: src.Size,
		Snapshots: src.Snapshots,
		Type: uint32(src.Type),
		VirtualSize: src.VirtualSize,
	}
}

// VolumeFromProto converts protobuf Volume to SRPC Volume
func VolumeFromProto(src *pb.Volume) *Volume {
	if src == nil {
		return nil
	}
	return &Volume{
		Format: VolumeFormat(src.Format),
		Interface: VolumeInterface(src.Interface),
		Size: src.Size,
		Snapshots: src.Snapshots,
		Type: VolumeType(src.Type),
		VirtualSize: src.VirtualSize,
	}
}

// Helper functions for []NetworkEntry conversion
func convertNetworkEntrySliceToProto(src []NetworkEntry) []*pb.NetworkEntry {
	if src == nil {
		return nil
	}
	result := make([]*pb.NetworkEntry, len(src))
	for i := range src {
		result[i] = NetworkEntryToProto(&src[i])
	}
	return result
}

func convertNetworkEntrySliceFromProto(src []*pb.NetworkEntry) []NetworkEntry {
	if src == nil {
		return nil
	}
	result := make([]NetworkEntry, len(src))
	for i, item := range src {
		if item != nil {
			result[i] = *NetworkEntryFromProto(item)
		}
	}
	return result
}

// Helper functions for []Address conversion
func convertAddressSliceToProto(src []Address) []*pb.Address {
	if src == nil {
		return nil
	}
	result := make([]*pb.Address, len(src))
	for i := range src {
		result[i] = AddressToProto(&src[i])
	}
	return result
}

func convertAddressSliceFromProto(src []*pb.Address) []Address {
	if src == nil {
		return nil
	}
	result := make([]Address, len(src))
	for i, item := range src {
		if item != nil {
			result[i] = *AddressFromProto(item)
		}
	}
	return result
}

// Helper functions for []Volume conversion
func convertVolumeSliceToProto(src []Volume) []*pb.Volume {
	if src == nil {
		return nil
	}
	result := make([]*pb.Volume, len(src))
	for i := range src {
		result[i] = VolumeToProto(&src[i])
	}
	return result
}

func convertVolumeSliceFromProto(src []*pb.Volume) []Volume {
	if src == nil {
		return nil
	}
	result := make([]Volume, len(src))
	for i, item := range src {
		if item != nil {
			result[i] = *VolumeFromProto(item)
		}
	}
	return result
}

