// Code generated by generate-rest-routes.sh. DO NOT EDIT.

package rpcd

import (
	"net/http"
	"strings"
)

// ExtractMethodFromPath maps HTTP paths to gRPC method names for REST auth.
// Generated from proto google.api.http annotations.
func ExtractMethodFromPath(path, httpMethod string) string {
	switch {
	case path == "/v1/vms" && httpMethod == http.MethodPost:
		return "CreateVm"
	case strings.HasSuffix(path, ":start") && httpMethod == http.MethodPost:
		return "StartVm"
	case strings.HasPrefix(path, "/v1/vms/") && httpMethod == http.MethodDelete:
		return "DestroyVm"
	case path == "/v1/vms" && httpMethod == http.MethodGet:
		return "ListVms"
	case strings.HasPrefix(path, "/v1/vms/") && httpMethod == http.MethodGet:
		return "GetVm"
	default:
		return "Unknown"
	}
}
