// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: common/grpc/common.proto

package common_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tags represents a set of key-value pairs for metadata.
// This mirrors lib/tags.Tags (map[string]string).
type Tags struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          map[string]string      `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tags) Reset() {
	*x = Tags{}
	mi := &file_common_grpc_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tags) ProtoMessage() {}

func (x *Tags) ProtoReflect() protoreflect.Message {
	mi := &file_common_grpc_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tags.ProtoReflect.Descriptor instead.
func (*Tags) Descriptor() ([]byte, []int) {
	return file_common_grpc_common_proto_rawDescGZIP(), []int{0}
}

func (x *Tags) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// MatchTags represents tag matching criteria.
// This mirrors lib/tags.MatchTags (map[string][]string).
// Key: tag key, value: values to OR match.
type MatchTags struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchTags     map[string]*StringList `protobuf:"bytes,1,rep,name=match_tags,json=matchTags,proto3" json:"match_tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchTags) Reset() {
	*x = MatchTags{}
	mi := &file_common_grpc_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchTags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchTags) ProtoMessage() {}

func (x *MatchTags) ProtoReflect() protoreflect.Message {
	mi := &file_common_grpc_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchTags.ProtoReflect.Descriptor instead.
func (*MatchTags) Descriptor() ([]byte, []int) {
	return file_common_grpc_common_proto_rawDescGZIP(), []int{1}
}

func (x *MatchTags) GetMatchTags() map[string]*StringList {
	if x != nil {
		return x.MatchTags
	}
	return nil
}

// StringList is a helper message for MatchTags since proto3 doesn't support
// map<string, repeated string> directly.
type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_common_grpc_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_common_grpc_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_common_grpc_common_proto_rawDescGZIP(), []int{2}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_common_grpc_common_proto protoreflect.FileDescriptor

const file_common_grpc_common_proto_rawDesc = "" +
	"\n" +
	"\x18common/grpc/common.proto\x12\x06common\"k\n" +
	"\x04Tags\x12*\n" +
	"\x04tags\x18\x01 \x03(\v2\x16.common.Tags.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9e\x01\n" +
	"\tMatchTags\x12?\n" +
	"\n" +
	"match_tags\x18\x01 \x03(\v2 .common.MatchTags.MatchTagsEntryR\tmatchTags\x1aP\n" +
	"\x0eMatchTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.common.StringListR\x05value:\x028\x01\"$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06valuesBFZDgithub.com/Cloud-Foundations/Dominator/proto/common/grpc;common_grpcb\x06proto3"

var (
	file_common_grpc_common_proto_rawDescOnce sync.Once
	file_common_grpc_common_proto_rawDescData []byte
)

func file_common_grpc_common_proto_rawDescGZIP() []byte {
	file_common_grpc_common_proto_rawDescOnce.Do(func() {
		file_common_grpc_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_grpc_common_proto_rawDesc), len(file_common_grpc_common_proto_rawDesc)))
	})
	return file_common_grpc_common_proto_rawDescData
}

var file_common_grpc_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_common_grpc_common_proto_goTypes = []any{
	(*Tags)(nil),       // 0: common.Tags
	(*MatchTags)(nil),  // 1: common.MatchTags
	(*StringList)(nil), // 2: common.StringList
	nil,                // 3: common.Tags.TagsEntry
	nil,                // 4: common.MatchTags.MatchTagsEntry
}
var file_common_grpc_common_proto_depIdxs = []int32{
	3, // 0: common.Tags.tags:type_name -> common.Tags.TagsEntry
	4, // 1: common.MatchTags.match_tags:type_name -> common.MatchTags.MatchTagsEntry
	2, // 2: common.MatchTags.MatchTagsEntry.value:type_name -> common.StringList
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_common_grpc_common_proto_init() }
func file_common_grpc_common_proto_init() {
	if File_common_grpc_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_grpc_common_proto_rawDesc), len(file_common_grpc_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_grpc_common_proto_goTypes,
		DependencyIndexes: file_common_grpc_common_proto_depIdxs,
		MessageInfos:      file_common_grpc_common_proto_msgTypes,
	}.Build()
	File_common_grpc_common_proto = out.File
	file_common_grpc_common_proto_goTypes = nil
	file_common_grpc_common_proto_depIdxs = nil
}
