package main

import (
	"fmt"
	"os"
	"strings"
)

func generateConverters(outputFile string, types []TypeInfo) error {
	f, err := os.Create(outputFile)
	if err != nil {
		return fmt.Errorf("failed to create file: %w", err)
	}
	defer f.Close()

	// Determine package name from types (assume all types are in same package)
	pkgName := "hypervisor" // Default

	// Write package header
	fmt.Fprintf(f, "package %s\n\n", pkgName)
	fmt.Fprintf(f, "// Code generated by proto-gen. DO NOT EDIT.\n\n")

	// Write imports
	fmt.Fprintf(f, "import (\n")
	fmt.Fprintf(f, "\t\"net\"\n")
	fmt.Fprintf(f, "\t\"time\"\n")
	fmt.Fprintf(f, "\n")
	fmt.Fprintf(f, "\t\"github.com/Cloud-Foundations/Dominator/lib/tags\"\n")
	fmt.Fprintf(f, "\tpb \"github.com/Cloud-Foundations/Dominator/proto/hypervisor/grpc\"\n")
	fmt.Fprintf(f, ")\n\n")

	// Generate converters for each type
	for _, typeInfo := range types {
		if err := generateConverter(f, typeInfo); err != nil {
			return err
		}
	}

	// Generate helper functions for slice conversions
	if err := generateSliceHelpers(f, types); err != nil {
		return err
	}

	return nil
}

func generateConverter(f *os.File, typeInfo TypeInfo) error {
	// Generate SRPC -> Proto converter
	fmt.Fprintf(f, "// %sToProto converts SRPC %s to protobuf %s\n",
		typeInfo.Name, typeInfo.Name, typeInfo.Name)
	fmt.Fprintf(f, "func %sToProto(src *%s) *pb.%s {\n",
		typeInfo.Name, typeInfo.Name, typeInfo.Name)
	fmt.Fprintf(f, "\tif src == nil {\n")
	fmt.Fprintf(f, "\t\treturn nil\n")
	fmt.Fprintf(f, "\t}\n")
	fmt.Fprintf(f, "\treturn &pb.%s{\n", typeInfo.Name)

	for _, field := range typeInfo.Fields {
		conversion := generateFieldConversion(field, "src", true)
		fmt.Fprintf(f, "\t\t%s: %s,\n", field.Name, conversion)
	}

	fmt.Fprintf(f, "\t}\n")
	fmt.Fprintf(f, "}\n\n")

	// Generate Proto -> SRPC converter
	fmt.Fprintf(f, "// %sFromProto converts protobuf %s to SRPC %s\n",
		typeInfo.Name, typeInfo.Name, typeInfo.Name)
	fmt.Fprintf(f, "func %sFromProto(src *pb.%s) *%s {\n",
		typeInfo.Name, typeInfo.Name, typeInfo.Name)
	fmt.Fprintf(f, "\tif src == nil {\n")
	fmt.Fprintf(f, "\t\treturn nil\n")
	fmt.Fprintf(f, "\t}\n")
	fmt.Fprintf(f, "\treturn &%s{\n", typeInfo.Name)

	for _, field := range typeInfo.Fields {
		conversion := generateFieldConversion(field, "src", false)
		fmt.Fprintf(f, "\t\t%s: %s,\n", field.Name, conversion)
	}

	fmt.Fprintf(f, "\t}\n")
	fmt.Fprintf(f, "}\n\n")

	return nil
}

// generateFieldConversion generates the conversion code for a single field
// toProto: true = SRPC -> Proto, false = Proto -> SRPC
func generateFieldConversion(field FieldInfo, srcVar string, toProto bool) string {
	srcField := fmt.Sprintf("%s.%s", srcVar, field.Name)

	// Handle different type conversions
	goType := field.GoType

	// Remove pointer prefix for type checking
	goType = strings.TrimPrefix(goType, "*")

	// Handle slices
	if strings.HasPrefix(goType, "[]") {
		elemType := strings.TrimPrefix(goType, "[]")
		return generateSliceConversion(field.Name, srcField, elemType, toProto)
	}

	// Handle maps
	if strings.HasPrefix(goType, "map[") {
		// For now, just copy maps directly (works for basic types)
		return srcField
	}

	// Handle specific type conversions
	switch goType {
	case "net.IP":
		if toProto {
			// net.IP -> bytes
			return fmt.Sprintf("[]byte(%s)", srcField)
		} else {
			// bytes -> net.IP
			return fmt.Sprintf("net.IP(%s)", srcField)
		}

	case "net.HardwareAddr":
		if toProto {
			// net.HardwareAddr -> bytes
			return fmt.Sprintf("[]byte(%s)", srcField)
		} else {
			// bytes -> net.HardwareAddr
			return fmt.Sprintf("net.HardwareAddr(%s)", srcField)
		}

	case "time.Time":
		if toProto {
			// time.Time -> int64 (Unix timestamp)
			return fmt.Sprintf("%s.Unix()", srcField)
		} else {
			// int64 -> time.Time
			return fmt.Sprintf("time.Unix(%s, 0)", srcField)
		}

	case "time.Duration":
		if toProto {
			// time.Duration -> int64 (nanoseconds)
			return fmt.Sprintf("int64(%s)", srcField)
		} else {
			// int64 -> time.Duration
			return fmt.Sprintf("time.Duration(%s)", srcField)
		}

	// Basic types that don't need conversion
	case "string", "bool":
		return srcField

	// Integer types - need explicit casts for size changes
	case "int":
		if toProto {
			return fmt.Sprintf("int32(%s)", srcField)
		} else {
			return fmt.Sprintf("int(%s)", srcField)
		}
	case "uint":
		if toProto {
			return fmt.Sprintf("uint32(%s)", srcField)
		} else {
			return fmt.Sprintf("uint(%s)", srcField)
		}
	case "int8", "int16":
		if toProto {
			return fmt.Sprintf("int32(%s)", srcField)
		} else {
			return fmt.Sprintf("%s(%s)", goType, srcField)
		}
	case "uint8", "uint16":
		if toProto {
			return fmt.Sprintf("uint32(%s)", srcField)
		} else {
			return fmt.Sprintf("%s(%s)", goType, srcField)
		}
	case "int32", "int64", "uint32", "uint64":
		return srcField

	// Float types
	case "float32", "float64":
		return srcField

	// Special external types
	case "tags.Tags":
		// tags.Tags is map[string]string, can be copied directly
		if toProto {
			return fmt.Sprintf("map[string]string(%s)", srcField)
		} else {
			return fmt.Sprintf("tags.Tags(%s)", srcField)
		}

	case "filter.Filter":
		// Filter is complex - for now, serialize to bytes
		// TODO: Implement proper filter conversion
		return srcField

	default:
		// Check if it's a qualified type from another package
		if strings.Contains(goType, ".") {
			// External type - assume converter exists
			if toProto {
				return fmt.Sprintf("%sToProto(&%s)", goType, srcField)
			} else {
				return fmt.Sprintf("%sFromProto(%s)", goType, srcField)
			}
		}

		// Custom type in same package
		// Check if it's a known enum type
		knownEnums := map[string]bool{
			"ConsoleType": true, "State": true, "FirmwareType": true, "MachineType": true,
			"VolumeFormat": true, "WatchdogAction": true, "WatchdogModel": true,
			"VolumeInterface": true, "VolumeType": true, "Interface": true, "Type": true,
		}

		if knownEnums[goType] {
			// Enum type - just cast
			if toProto {
				return fmt.Sprintf("uint32(%s)", srcField)
			} else {
				return fmt.Sprintf("%s(%s)", goType, srcField)
			}
		}

		// Complex type - use converter
		if toProto {
			return fmt.Sprintf("%sToProto(&%s)", goType, srcField)
		} else {
			// FromProto returns a pointer, dereference it
			return fmt.Sprintf("*%sFromProto(%s)", goType, srcField)
		}
	}
}

// generateSliceConversion generates conversion code for slice fields
func generateSliceConversion(fieldName, srcField, elemType string, toProto bool) string {
	// Remove pointer prefix
	elemType = strings.TrimPrefix(elemType, "*")

	// For basic types, we can copy directly
	switch elemType {
	case "string", "bool", "int32", "int64", "uint32", "uint64", "float32", "float64", "byte":
		return srcField

	case "net.IP":
		// []net.IP needs element-wise conversion
		if toProto {
			return fmt.Sprintf("convertIPSliceToProto(%s)", srcField)
		} else {
			return fmt.Sprintf("convertIPSliceFromProto(%s)", srcField)
		}

	case "net.HardwareAddr":
		// []net.HardwareAddr needs element-wise conversion
		if toProto {
			return fmt.Sprintf("convertHardwareAddrSliceToProto(%s)", srcField)
		} else {
			return fmt.Sprintf("convertHardwareAddrSliceFromProto(%s)", srcField)
		}

	default:
		// Custom type - needs element-wise conversion
		if toProto {
			return fmt.Sprintf("convert%sSliceToProto(%s)", elemType, srcField)
		} else {
			return fmt.Sprintf("convert%sSliceFromProto(%s)", elemType, srcField)
		}
	}
}

// generateSliceHelpers generates helper functions for slice conversions
func generateSliceHelpers(f *os.File, types []TypeInfo) error {
	// Track which helpers we've generated
	generated := make(map[string]bool)

	// Collect all slice types that need helpers
	sliceTypes := make(map[string]bool)

	for _, typeInfo := range types {
		for _, field := range typeInfo.Fields {
			goType := strings.TrimPrefix(field.GoType, "*")
			if strings.HasPrefix(goType, "[]") {
				elemType := strings.TrimPrefix(goType, "[]")
				elemType = strings.TrimPrefix(elemType, "*")

				// Check if this type needs a helper
				needsHelper := false
				switch elemType {
				case "string", "bool", "int32", "int64", "uint32", "uint64", "float32", "float64", "byte":
					// Basic types don't need helpers
				case "net.IP", "net.HardwareAddr":
					needsHelper = true
				default:
					// Custom types need helpers
					if !strings.Contains(elemType, ".") {
						needsHelper = true
					}
				}

				if needsHelper {
					sliceTypes[elemType] = true
				}
			}
		}
	}

	// Generate helpers for net.IP
	if sliceTypes["net.IP"] && !generated["net.IP"] {
		fmt.Fprintf(f, "// Helper functions for []net.IP conversion\n")
		fmt.Fprintf(f, "func convertIPSliceToProto(src []net.IP) [][]byte {\n")
		fmt.Fprintf(f, "\tif src == nil {\n")
		fmt.Fprintf(f, "\t\treturn nil\n")
		fmt.Fprintf(f, "\t}\n")
		fmt.Fprintf(f, "\tresult := make([][]byte, len(src))\n")
		fmt.Fprintf(f, "\tfor i, ip := range src {\n")
		fmt.Fprintf(f, "\t\tresult[i] = []byte(ip)\n")
		fmt.Fprintf(f, "\t}\n")
		fmt.Fprintf(f, "\treturn result\n")
		fmt.Fprintf(f, "}\n\n")

		fmt.Fprintf(f, "func convertIPSliceFromProto(src [][]byte) []net.IP {\n")
		fmt.Fprintf(f, "\tif src == nil {\n")
		fmt.Fprintf(f, "\t\treturn nil\n")
		fmt.Fprintf(f, "\t}\n")
		fmt.Fprintf(f, "\tresult := make([]net.IP, len(src))\n")
		fmt.Fprintf(f, "\tfor i, b := range src {\n")
		fmt.Fprintf(f, "\t\tresult[i] = net.IP(b)\n")
		fmt.Fprintf(f, "\t}\n")
		fmt.Fprintf(f, "\treturn result\n")
		fmt.Fprintf(f, "}\n\n")

		generated["net.IP"] = true
	}

	// Generate helpers for net.HardwareAddr
	if sliceTypes["net.HardwareAddr"] && !generated["net.HardwareAddr"] {
		fmt.Fprintf(f, "// Helper functions for []net.HardwareAddr conversion\n")
		fmt.Fprintf(f, "func convertHardwareAddrSliceToProto(src []net.HardwareAddr) [][]byte {\n")
		fmt.Fprintf(f, "\tif src == nil {\n")
		fmt.Fprintf(f, "\t\treturn nil\n")
		fmt.Fprintf(f, "\t}\n")
		fmt.Fprintf(f, "\tresult := make([][]byte, len(src))\n")
		fmt.Fprintf(f, "\tfor i, addr := range src {\n")
		fmt.Fprintf(f, "\t\tresult[i] = []byte(addr)\n")
		fmt.Fprintf(f, "\t}\n")
		fmt.Fprintf(f, "\treturn result\n")
		fmt.Fprintf(f, "}\n\n")

		fmt.Fprintf(f, "func convertHardwareAddrSliceFromProto(src [][]byte) []net.HardwareAddr {\n")
		fmt.Fprintf(f, "\tif src == nil {\n")
		fmt.Fprintf(f, "\t\treturn nil\n")
		fmt.Fprintf(f, "\t}\n")
		fmt.Fprintf(f, "\tresult := make([]net.HardwareAddr, len(src))\n")
		fmt.Fprintf(f, "\tfor i, b := range src {\n")
		fmt.Fprintf(f, "\t\tresult[i] = net.HardwareAddr(b)\n")
		fmt.Fprintf(f, "\t}\n")
		fmt.Fprintf(f, "\treturn result\n")
		fmt.Fprintf(f, "}\n\n")

		generated["net.HardwareAddr"] = true
	}

	// Generate helpers for custom types
	for elemType := range sliceTypes {
		if generated[elemType] {
			continue
		}

		// Skip external types
		if strings.Contains(elemType, ".") {
			continue
		}

		fmt.Fprintf(f, "// Helper functions for []%s conversion\n", elemType)
		fmt.Fprintf(f, "func convert%sSliceToProto(src []%s) []*pb.%s {\n", elemType, elemType, elemType)
		fmt.Fprintf(f, "\tif src == nil {\n")
		fmt.Fprintf(f, "\t\treturn nil\n")
		fmt.Fprintf(f, "\t}\n")
		fmt.Fprintf(f, "\tresult := make([]*pb.%s, len(src))\n", elemType)
		fmt.Fprintf(f, "\tfor i := range src {\n")
		fmt.Fprintf(f, "\t\tresult[i] = %sToProto(&src[i])\n", elemType)
		fmt.Fprintf(f, "\t}\n")
		fmt.Fprintf(f, "\treturn result\n")
		fmt.Fprintf(f, "}\n\n")

		fmt.Fprintf(f, "func convert%sSliceFromProto(src []*pb.%s) []%s {\n", elemType, elemType, elemType)
		fmt.Fprintf(f, "\tif src == nil {\n")
		fmt.Fprintf(f, "\t\treturn nil\n")
		fmt.Fprintf(f, "\t}\n")
		fmt.Fprintf(f, "\tresult := make([]%s, len(src))\n", elemType)
		fmt.Fprintf(f, "\tfor i, item := range src {\n")
		fmt.Fprintf(f, "\t\tif item != nil {\n")
		fmt.Fprintf(f, "\t\t\tresult[i] = *%sFromProto(item)\n", elemType)
		fmt.Fprintf(f, "\t\t}\n")
		fmt.Fprintf(f, "\t}\n")
		fmt.Fprintf(f, "\treturn result\n")
		fmt.Fprintf(f, "}\n\n")

		generated[elemType] = true
	}

	return nil
}
