package main

import (
	"fmt"
	"os"
	"strings"
)

func generateProto(outputFile string, types []TypeInfo, methods []MethodInfo, imports map[string]string) error {
	f, err := os.Create(outputFile)
	if err != nil {
		return fmt.Errorf("failed to create file: %w", err)
	}
	defer f.Close()

	// Write warning header
	fmt.Fprintf(f, "// Code generated by proto-gen. DO NOT EDIT.\n")
	fmt.Fprintf(f, "// Source: SRPC method definitions in rpcd/\n")
	fmt.Fprintf(f, "//\n")
	fmt.Fprintf(f, "// To regenerate this file, run:\n")
	fmt.Fprintf(f, "//   make proto-gen\n")
	fmt.Fprintf(f, "// or:\n")
	fmt.Fprintf(f, "//   proto-gen --rpcd <rpcd-dir> --proto <proto-dir> --output <output-file>\n")
	fmt.Fprintf(f, "\n")

	// Write proto header
	fmt.Fprintf(f, "syntax = \"proto3\";\n\n")
	fmt.Fprintf(f, "package %s;\n\n", getPackageNameFromFile(outputFile))
	fmt.Fprintf(f, "option go_package = \".;pb\";\n\n")

	// Write import statements for cross-package types
	if len(imports) > 0 {
		for _, protoPath := range imports {
			fmt.Fprintf(f, "import \"%s\";\n", protoPath)
		}
		fmt.Fprintf(f, "\n")
	}

	// TODO: Import google/api/annotations.proto for HTTP annotations
	// Commented out for now - requires googleapis proto files
	// if hasHttpAnnotations(methods) {
	// 	fmt.Fprintf(f, "import \"google/api/annotations.proto\";\n\n")
	// }

	// Generate message definitions
	for _, typeInfo := range types {
		if err := generateMessage(f, typeInfo); err != nil {
			return err
		}
	}

	// Generate service definition
	if len(methods) > 0 {
		if err := generateService(f, methods); err != nil {
			return err
		}
	}

	return nil
}

func generateMessage(f *os.File, typeInfo TypeInfo) error {
	fmt.Fprintf(f, "message %s {\n", typeInfo.Name)

	for _, field := range typeInfo.Fields {
		// Generate field
		repeated := ""
		if field.IsRepeated {
			repeated = "repeated "
		}

		// Use the original field name (no snake_case conversion)
		fmt.Fprintf(f, "  %s%s %s = %d;\n",
			repeated,
			field.ProtoType,
			field.Name,
			field.ProtoNumber)
	}

	fmt.Fprintf(f, "}\n\n")
	return nil
}

func generateService(f *os.File, methods []MethodInfo) error {
	// Determine service name from first method
	serviceName := "Service"
	if len(methods) > 0 {
		// Extract service name from method name (e.g., GetVmInfo -> Vm)
		serviceName = extractServiceName(methods[0].Name)
	}

	fmt.Fprintf(f, "service %s {\n", serviceName)

	for _, method := range methods {
		// Generate RPC method
		fmt.Fprintf(f, "  rpc %s(%s) returns (%s);\n",
			method.GrpcName,
			method.RequestType,
			method.ResponseType)

		// TODO: Add HTTP annotation if present (requires google/api/annotations.proto)
		// if method.HttpMethod != "" {
		// 	fmt.Fprintf(f, " {\n")
		// 	fmt.Fprintf(f, "    option (google.api.http) = {\n")
		// 	fmt.Fprintf(f, "      %s: \"%s\"\n",
		// 		strings.ToLower(method.HttpMethod),
		// 		method.HttpPath)
		//
		// 	if method.HttpBody != "" {
		// 		fmt.Fprintf(f, "      body: \"%s\"\n", method.HttpBody)
		// 	}
		//
		// 	fmt.Fprintf(f, "    };\n")
		// 	fmt.Fprintf(f, "  }\n")
		// } else {
		// 	fmt.Fprintf(f, ";\n")
		// }
	}

	fmt.Fprintf(f, "}\n\n")
	return nil
}

func hasHttpAnnotations(methods []MethodInfo) bool {
	for _, method := range methods {
		if method.HttpMethod != "" {
			return true
		}
	}
	return false
}

func getPackageNameFromFile(filename string) string {
	// Extract package name from filename
	// e.g., "/path/to/hypervisor.proto" -> "hypervisor"
	parts := strings.Split(filename, "/")
	if len(parts) == 0 {
		return "unknown"
	}
	name := parts[len(parts)-1]
	return strings.TrimSuffix(name, ".proto")
}

func extractServiceName(methodName string) string {
	// Try to extract service name from method name
	// e.g., "GetVmInfo" -> "Hypervisor"
	// For now, just return a generic name
	return "Hypervisor"
}
