#!/bin/bash
# Generates Go code that maps REST HTTP paths to gRPC method names.
# Parses google.api.http annotations from proto files.
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Parse proto file and extract HTTP annotations
generate_routes() {
    local proto_file="$1"
    local package_name="$2"
    local output_file="$3"
    
    # Extract service name
    local service_name=$(grep -E "^service " "$proto_file" | head -1 | awk '{print $2}')
    [ -z "$service_name" ] && return
    
    # Extract rpc methods with their HTTP annotations
    local in_rpc=""
    local rpc_name=""
    local http_method=""
    local http_path=""
    local routes=()
    
    while IFS= read -r line; do
        # Match rpc declaration
        if [[ "$line" =~ ^[[:space:]]*rpc[[:space:]]+([A-Za-z0-9_]+) ]]; then
            rpc_name="${BASH_REMATCH[1]}"
            in_rpc="true"
        fi

        # Match HTTP method and path
        if [[ "$in_rpc" == "true" ]]; then
            if [[ "$line" =~ (get|post|put|delete|patch):[[:space:]]*\"([^\"]+)\" ]]; then
                http_method="${BASH_REMATCH[1]}"
                http_path="${BASH_REMATCH[2]}"
                # Use | as delimiter since paths may contain :
                routes+=("$http_method|$http_path|$rpc_name")
            fi
            # End of rpc block
            if [[ "$line" =~ \}\; ]]; then
                in_rpc=""
                rpc_name=""
            fi
        fi
    done < "$proto_file"
    
    [ ${#routes[@]} -eq 0 ] && return
    
    # Generate Go code
    cat > "$output_file" << 'HEADER'
// Code generated by generate-rest-routes.sh. DO NOT EDIT.

package rpcd

import (
	"net/http"
	"strings"
)

// ExtractMethodFromPath maps HTTP paths to gRPC method names for REST auth.
// Generated from proto google.api.http annotations.
func ExtractMethodFromPath(path, httpMethod string) string {
HEADER

    # Generate switch cases
    echo "	switch {" >> "$output_file"
    
    for route in "${routes[@]}"; do
        IFS='|' read -r method path_pattern rpc <<< "$route"
        
        # Convert HTTP method to Go constant
        case "$method" in
            get)    go_method="http.MethodGet" ;;
            post)   go_method="http.MethodPost" ;;
            put)    go_method="http.MethodPut" ;;
            delete) go_method="http.MethodDelete" ;;
            patch)  go_method="http.MethodPatch" ;;
        esac
        
        # Handle path patterns:
        # - Exact match: /v1/vms
        # - Prefix with param: /v1/vms/{ip_address}
        # - Custom verb: /v1/vms/{ip_address}:start

        if [[ "$path_pattern" == *":"* ]]; then
            # Custom verb pattern like /v1/vms/{ip_address}:start
            verb="${path_pattern##*:}"
            echo "	case strings.HasSuffix(path, \":$verb\") && httpMethod == $go_method:" >> "$output_file"
        elif [[ "$path_pattern" == *"{"* ]]; then
            # Path with parameter like /v1/vms/{ip_address}
            prefix="${path_pattern%%\{*}"
            echo "	case strings.HasPrefix(path, \"$prefix\") && httpMethod == $go_method:" >> "$output_file"
        else
            # Exact path match
            echo "	case path == \"$path_pattern\" && httpMethod == $go_method:" >> "$output_file"
        fi
        echo "		return \"$rpc\"" >> "$output_file"
    done
    
    echo "	default:" >> "$output_file"
    echo "		return \"Unknown\"" >> "$output_file"
    echo "	}" >> "$output_file"
    echo "}" >> "$output_file"
    
    # Format the generated code
    gofmt -w "$output_file" 2>/dev/null || true
    
    echo "Generated $output_file"
}

# Generate for hypervisor service
generate_routes \
    "$REPO_ROOT/proto/hypervisor/grpc/hypervisor.proto" \
    "rpcd" \
    "$REPO_ROOT/hypervisor/rpcd/rest_routes_generated.go"

